// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Result from "rescript/lib/es6/belt_Result.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Result from "@rescript/core/src/Core__Result.mjs";
import * as TableclothList from "./TableclothList.mjs";
import * as CamlinternalLazy from "rescript/lib/es6/camlinternalLazy.js";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";

function ok(a) {
  return {
          TAG: "Ok",
          _0: a
        };
}

function error(e) {
  return {
          TAG: "Error",
          _0: e
        };
}

function fromOption(ma, error) {
  if (ma !== undefined) {
    return {
            TAG: "Ok",
            _0: Caml_option.valFromOption(ma)
          };
  } else {
    return {
            TAG: "Error",
            _0: error
          };
  }
}

function both(a, b) {
  if (a.TAG === "Ok") {
    if (b.TAG === "Ok") {
      return {
              TAG: "Ok",
              _0: [
                a._0,
                b._0
              ]
            };
    } else {
      return {
              TAG: "Error",
              _0: b._0
            };
    }
  } else {
    return {
            TAG: "Error",
            _0: a._0
          };
  }
}

function flatten(a) {
  if (a.TAG === "Ok") {
    return a._0;
  } else {
    return {
            TAG: "Error",
            _0: a._0
          };
  }
}

function orElse(a, b) {
  if (a.TAG === "Ok") {
    return a;
  } else {
    return b;
  }
}

function and_(a, b) {
  if (a.TAG === "Ok") {
    return b;
  } else {
    return a;
  }
}

function unwrapLazy(t, $$default) {
  if (t.TAG === "Ok") {
    return t._0;
  } else {
    return CamlinternalLazy.force($$default);
  }
}

var unwrapUnsafe = Belt_Result.getExn;

function unwrapError(t, $$default) {
  if (t.TAG === "Ok") {
    return $$default;
  } else {
    return t._0;
  }
}

function map2(a, b, f) {
  if (a.TAG === "Ok") {
    if (b.TAG === "Ok") {
      return {
              TAG: "Ok",
              _0: f(a._0, b._0)
            };
    } else {
      return {
              TAG: "Error",
              _0: b._0
            };
    }
  } else {
    return {
            TAG: "Error",
            _0: a._0
          };
  }
}

function values(t) {
  return TableclothList.foldRight(t, {
              TAG: "Ok",
              _0: /* [] */0
            }, (function (c, d) {
                return map2(d, c, (function (a, b) {
                              return {
                                      hd: a,
                                      tl: b
                                    };
                            }));
              }));
}

function combine(l) {
  return TableclothList.foldRight(l, {
              TAG: "Ok",
              _0: /* [] */0
            }, (function (accum, value) {
                return map2(value, accum, (function (head, list) {
                              return {
                                      hd: head,
                                      tl: list
                                    };
                            }));
              }));
}

function toOption(r) {
  if (r.TAG === "Ok") {
    return Caml_option.some(r._0);
  }
  
}

function attempt(f) {
  var value;
  try {
    value = f();
  }
  catch (raw_error){
    var error = Caml_js_exceptions.internalToOCamlException(raw_error);
    return {
            TAG: "Error",
            _0: error
          };
  }
  return {
          TAG: "Ok",
          _0: value
        };
}

function tap(t, f) {
  if (t.TAG === "Ok") {
    return f(t._0);
  }
  
}

var or_ = orElse;

var unwrap = Core__Result.getOr;

var map = Core__Result.map;

var mapError = Core__Result.mapError;

var andThen = Core__Result.flatMap;

export {
  ok ,
  error ,
  attempt ,
  fromOption ,
  and_ ,
  or_ ,
  orElse ,
  both ,
  flatten ,
  unwrap ,
  unwrapLazy ,
  unwrapUnsafe ,
  unwrapError ,
  map2 ,
  values ,
  combine ,
  map ,
  mapError ,
  andThen ,
  tap ,
  toOption ,
}
/* TableclothList Not a pure module */
