// Generated by ReScript, PLEASE EDIT WITH CARE


function make(a, b, c) {
  return [
    a,
    b,
    c
  ];
}

function fromArray(array) {
  let len = array.length;
  if (len >= 4) {
    return [
      array[0],
      array[1],
      array[2]
    ];
  }
  switch (len) {
    case 0 :
    case 1 :
    case 2 :
      return;
    case 3 :
      let a = array[0];
      let b = array[1];
      let c = array[2];
      return [
        a,
        b,
        c
      ];
  }
}

function fromList(list) {
  if (!list) {
    return;
  }
  let match = list.tl;
  if (!match) {
    return;
  }
  let match$1 = match.tl;
  if (match$1) {
    return [
      list.hd,
      match.hd,
      match$1.hd
    ];
  }
  
}

function first(param) {
  return param[0];
}

function second(param) {
  return param[1];
}

function third(param) {
  return param[2];
}

function initial(param) {
  return [
    param[0],
    param[1]
  ];
}

function tail(param) {
  return [
    param[1],
    param[2]
  ];
}

function mapFirst(param, f) {
  return [
    f(param[0]),
    param[1],
    param[2]
  ];
}

function mapSecond(param, f) {
  return [
    param[0],
    f(param[1]),
    param[2]
  ];
}

function mapThird(param, f) {
  return [
    param[0],
    param[1],
    f(param[2])
  ];
}

function mapEach(param, f, g, h) {
  return [
    f(param[0]),
    g(param[1]),
    h(param[2])
  ];
}

function mapAll(param, f) {
  return [
    f(param[0]),
    f(param[1]),
    f(param[2])
  ];
}

function rotateLeft(param) {
  return [
    param[1],
    param[2],
    param[0]
  ];
}

function rotateRight(param) {
  return [
    param[2],
    param[0],
    param[1]
  ];
}

function toArray(param) {
  return [
    param[0],
    param[1],
    param[2]
  ];
}

function toList(param) {
  return {
    hd: param[0],
    tl: {
      hd: param[1],
      tl: {
        hd: param[2],
        tl: /* [] */0
      }
    }
  };
}

function equal(param, param$1, equalFirst, equalSecond, equalThird) {
  if (equalFirst(param[0], param$1[0]) && equalSecond(param[1], param$1[1])) {
    return equalThird(param[2], param$1[2]);
  } else {
    return false;
  }
}

function compare(param, param$1, compareFirst, compareSecond, compareThird) {
  let result = compareFirst(param[0], param$1[0]);
  if (result !== 0) {
    return result;
  }
  let result$1 = compareSecond(param[1], param$1[1]);
  if (result$1 !== 0) {
    return result$1;
  } else {
    return compareThird(param[2], param$1[2]);
  }
}

export {
  make,
  fromArray,
  fromList,
  first,
  second,
  third,
  initial,
  tail,
  rotateLeft,
  rotateRight,
  mapFirst,
  mapSecond,
  mapThird,
  mapEach,
  mapAll,
  toArray,
  toList,
  equal,
  compare,
}
/* No side effect */
