// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__BigInt from "@rescript/core/src/Core__BigInt.mjs";

let toInt = Core__BigInt.toInt;

let lnot = Core__BigInt.lnot;

export {
  toInt,
  lnot,
}
/* No side effect */
