// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TableclothChar from "./Tablecloth/TableclothChar.mjs";

let fromCode = TableclothChar.fromCode;

let fromString = TableclothChar.fromString;

let isLowercase = TableclothChar.isLowercase;

let isUppercase = TableclothChar.isUppercase;

let isLetter = TableclothChar.isLetter;

let isDigit = TableclothChar.isDigit;

let isAlphanumeric = TableclothChar.isAlphanumeric;

let isPrintable = TableclothChar.isPrintable;

let isWhitespace = TableclothChar.isWhitespace;

let toLowercase = TableclothChar.toLowercase;

let toUppercase = TableclothChar.toUppercase;

let toCode = TableclothChar.toCode;

let toString = TableclothChar.toString;

let toDigit = TableclothChar.toDigit;

let equal = TableclothChar.equal;

let compare = TableclothChar.compare;

let comparator = TableclothChar.comparator;

export {
  fromCode,
  fromString,
  isLowercase,
  isUppercase,
  isLetter,
  isDigit,
  isAlphanumeric,
  isPrintable,
  isWhitespace,
  toLowercase,
  toUppercase,
  toCode,
  toString,
  toDigit,
  equal,
  compare,
  comparator,
}
/* TableclothChar Not a pure module */
