// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TableclothTuple3 from "./Tablecloth/TableclothTuple3.mjs";

let make = TableclothTuple3.make;

let fromArray = TableclothTuple3.fromArray;

let fromList = TableclothTuple3.fromList;

let first = TableclothTuple3.first;

let second = TableclothTuple3.second;

let third = TableclothTuple3.third;

let initial = TableclothTuple3.initial;

let tail = TableclothTuple3.tail;

let rotateLeft = TableclothTuple3.rotateLeft;

let rotateRight = TableclothTuple3.rotateRight;

let mapFirst = TableclothTuple3.mapFirst;

let mapSecond = TableclothTuple3.mapSecond;

let mapThird = TableclothTuple3.mapThird;

let mapEach = TableclothTuple3.mapEach;

let mapAll = TableclothTuple3.mapAll;

let toArray = TableclothTuple3.toArray;

let toList = TableclothTuple3.toList;

let equal = TableclothTuple3.equal;

let compare = TableclothTuple3.compare;

export {
  make,
  fromArray,
  fromList,
  first,
  second,
  third,
  initial,
  tail,
  rotateLeft,
  rotateRight,
  mapFirst,
  mapSecond,
  mapThird,
  mapEach,
  mapAll,
  toArray,
  toList,
  equal,
  compare,
}
/* No side effect */
