// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TableclothFun from "./Tablecloth/TableclothFun.mjs";

function id(a) {
  return a;
}

function coerce(prim) {
  return prim;
}

function eq(x, y) {
  return x === y;
}

function $$const(a, param) {
  return a;
}

function on(b, u, x, y) {
  return b(u(x), u(y));
}

function applyWhen(condition, f, x) {
  if (condition) {
    return f(x);
  } else {
    return x;
  }
}

function composeU(f, g, x) {
  return g(f(x));
}

function compose(f, g, x) {
  return g(f(x));
}

function composeRight(f, g, x) {
  return f(g(x));
}

function compose3(f, g, h, x) {
  return h(g(f(x)));
}

function compose4(f, g, h, i, x) {
  return i(h(g(f(x))));
}

let complement = TableclothFun.negate;

export {
  id,
  coerce,
  eq,
  $$const,
  complement,
  on,
  applyWhen,
  composeU,
  compose,
  composeRight,
  compose3,
  compose4,
}
/* No side effect */
