// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib__Set_Ext from "./Stdlib__Set_Ext.res.mjs";

let Serializable = Stdlib__Set_Ext.Serializable;

let JSONSerializable = Stdlib__Set_Ext.JSONSerializable;

let Make = Stdlib__Set_Ext.Make;

let Key = Stdlib__Set_Ext.Key;

export {
  Serializable,
  JSONSerializable,
  Make,
  Key,
}
/* Stdlib__Set_Ext Not a pure module */
