// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TableclothChar from "./Tablecloth/TableclothChar.mjs";

var fromCode = TableclothChar.fromCode;

var fromString = TableclothChar.fromString;

var isLowercase = TableclothChar.isLowercase;

var isUppercase = TableclothChar.isUppercase;

var isLetter = TableclothChar.isLetter;

var isDigit = TableclothChar.isDigit;

var isAlphanumeric = TableclothChar.isAlphanumeric;

var isPrintable = TableclothChar.isPrintable;

var isWhitespace = TableclothChar.isWhitespace;

var toLowercase = TableclothChar.toLowercase;

var toUppercase = TableclothChar.toUppercase;

var toCode = TableclothChar.toCode;

var toString = TableclothChar.toString;

var toDigit = TableclothChar.toDigit;

var equal = TableclothChar.equal;

var compare = TableclothChar.compare;

var comparator = TableclothChar.comparator;

export {
  fromCode ,
  fromString ,
  isLowercase ,
  isUppercase ,
  isLetter ,
  isDigit ,
  isAlphanumeric ,
  isPrintable ,
  isWhitespace ,
  toLowercase ,
  toUppercase ,
  toCode ,
  toString ,
  toDigit ,
  equal ,
  compare ,
  comparator ,
}
/* TableclothChar Not a pure module */
