// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Set from "rescript/lib/es6/Stdlib_Set.js";
import * as Stdlib__Set_Ext from "./Stdlib__Set_Ext.res.mjs";

let isEmpty = Stdlib_Set.isEmpty;

let Serializable = Stdlib__Set_Ext.Serializable;

let JSONSerializable = Stdlib__Set_Ext.JSONSerializable;

let MakeWithPrimitive = Stdlib__Set_Ext.MakeWithPrimitive;

let Make = Stdlib__Set_Ext.Make;

let Value = Stdlib__Set_Ext.Value;

export {
  isEmpty,
  Serializable,
  JSONSerializable,
  MakeWithPrimitive,
  Make,
  Value,
}
/* Stdlib__Set_Ext Not a pure module */
