// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TableclothFun from "./Tablecloth/TableclothFun.mjs";
import * as Stdlib__Function_Ext from "./Stdlib__Function_Ext.mjs";

var constant = TableclothFun.constant;

var sequence = TableclothFun.sequence;

var flip = TableclothFun.flip;

var negate = TableclothFun.negate;

var apply = TableclothFun.apply;

var tap = TableclothFun.tap;

var forever = TableclothFun.forever;

var times = TableclothFun.times;

var curry = TableclothFun.curry;

var uncurry = TableclothFun.uncurry;

var curry3 = TableclothFun.curry3;

var uncurry3 = TableclothFun.uncurry3;

var id = Stdlib__Function_Ext.id;

var coerce = Stdlib__Function_Ext.coerce;

var eq = Stdlib__Function_Ext.eq;

var $$const = Stdlib__Function_Ext.$$const;

var complement = Stdlib__Function_Ext.complement;

var on = Stdlib__Function_Ext.on;

var applyWhen = Stdlib__Function_Ext.applyWhen;

var composeU = Stdlib__Function_Ext.composeU;

var compose = Stdlib__Function_Ext.compose;

var composeRight = Stdlib__Function_Ext.composeRight;

var compose3 = Stdlib__Function_Ext.compose3;

var compose4 = Stdlib__Function_Ext.compose4;

export {
  constant ,
  sequence ,
  flip ,
  negate ,
  apply ,
  tap ,
  forever ,
  times ,
  curry ,
  uncurry ,
  curry3 ,
  uncurry3 ,
  id ,
  coerce ,
  eq ,
  $$const ,
  complement ,
  on ,
  applyWhen ,
  composeU ,
  compose ,
  composeRight ,
  compose3 ,
  compose4 ,
}
/* No side effect */
