// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_List from "rescript/lib/es6/Stdlib_List.js";
import * as TableclothList from "./Tablecloth/TableclothList.res.mjs";
import * as Stdlib__List_Ext from "./Stdlib__List_Ext.res.mjs";

let length = Stdlib_List.length;

let size = Stdlib_List.size;

let head = Stdlib_List.head;

let headExn = Stdlib_List.headExn;

let tail = Stdlib_List.tail;

let tailExn = Stdlib_List.tailExn;

let add = Stdlib_List.add;

let get = Stdlib_List.get;

let getExn = Stdlib_List.getExn;

let make = Stdlib_List.make;

let fromInitializer = Stdlib_List.fromInitializer;

let shuffle = Stdlib_List.shuffle;

let toShuffled = Stdlib_List.toShuffled;

let splitAt = Stdlib_List.splitAt;

let concat = Stdlib_List.concat;

let concatMany = Stdlib_List.concatMany;

let reverseConcat = Stdlib_List.reverseConcat;

let flat = Stdlib_List.flat;

let map = Stdlib_List.map;

let zip = Stdlib_List.zip;

let zipBy = Stdlib_List.zipBy;

let mapWithIndex = Stdlib_List.mapWithIndex;

let fromArray = Stdlib_List.fromArray;

let toArray = Stdlib_List.toArray;

let reverse = Stdlib_List.reverse;

let mapReverse = Stdlib_List.mapReverse;

let forEach = Stdlib_List.forEach;

let forEachWithIndex = Stdlib_List.forEachWithIndex;

let reduce = Stdlib_List.reduce;

let reduceWithIndex = Stdlib_List.reduceWithIndex;

let reduceReverse = Stdlib_List.reduceReverse;

let mapReverse2 = Stdlib_List.mapReverse2;

let forEach2 = Stdlib_List.forEach2;

let reduce2 = Stdlib_List.reduce2;

let reduceReverse2 = Stdlib_List.reduceReverse2;

let every = Stdlib_List.every;

let some = Stdlib_List.some;

let every2 = Stdlib_List.every2;

let some2 = Stdlib_List.some2;

let compareLength = Stdlib_List.compareLength;

let compare = Stdlib_List.compare;

let equal = Stdlib_List.equal;

let has = Stdlib_List.has;

let filter = Stdlib_List.filter;

let filterWithIndex = Stdlib_List.filterWithIndex;

let filterMap = Stdlib_List.filterMap;

let partition = Stdlib_List.partition;

let unzip = Stdlib_List.unzip;

let getAssoc = Stdlib_List.getAssoc;

let hasAssoc = Stdlib_List.hasAssoc;

let removeAssoc = Stdlib_List.removeAssoc;

let setAssoc = Stdlib_List.setAssoc;

let sort = Stdlib_List.sort;

let empty = TableclothList.empty;

let singleton = TableclothList.singleton;

let repeat = TableclothList.repeat;

let range = TableclothList.range;

let initialize = TableclothList.initialize;

let cons = TableclothList.cons;

let take = TableclothList.take;

let takeWhile = TableclothList.takeWhile;

let drop = TableclothList.drop;

let dropWhile = TableclothList.dropWhile;

let initial = TableclothList.initial;

let last = TableclothList.last;

let getAt = TableclothList.getAt;

let insertAt = TableclothList.insertAt;

let updateAt = TableclothList.updateAt;

let removeAt = TableclothList.removeAt;

let sortBy = TableclothList.sortBy;

let isEmpty = TableclothList.isEmpty;

let any = TableclothList.any;

let all = TableclothList.all;

let count = TableclothList.count;

let uniqueBy = TableclothList.uniqueBy;

let find = TableclothList.find;

let findIndex = TableclothList.findIndex;

let includes = TableclothList.includes;

let minimumBy = TableclothList.minimumBy;

let maximumBy = TableclothList.maximumBy;

let minimum = TableclothList.minimum;

let maximum = TableclothList.maximum;

let extent = TableclothList.extent;

let sum = TableclothList.sum;

let flatMap = TableclothList.flatMap;

let fold = TableclothList.fold;

let foldRight = TableclothList.foldRight;

let append = TableclothList.append;

let map2 = TableclothList.map2;

let map3 = TableclothList.map3;

let splitWhen = TableclothList.splitWhen;

let intersperse = TableclothList.intersperse;

let chunksOf = TableclothList.chunksOf;

let sliding = TableclothList.sliding;

let groupWhile = TableclothList.groupWhile;

let join = TableclothList.join;

let groupBy = TableclothList.groupBy;

let L = Stdlib__List_Ext.L;

let listToOption = Stdlib__List_Ext.listToOption;

let foldLeft0 = Stdlib__List_Ext.foldLeft0;

let foldRight0 = Stdlib__List_Ext.foldRight0;

let transpose = Stdlib__List_Ext.transpose;

let zipWith = Stdlib__List_Ext.zipWith;

let combinationIf2 = Stdlib__List_Ext.combinationIf2;

let combination2 = Stdlib__List_Ext.combination2;

let unfold = Stdlib__List_Ext.unfold;

export {
  length,
  size,
  head,
  headExn,
  tail,
  tailExn,
  add,
  get,
  getExn,
  make,
  fromInitializer,
  shuffle,
  toShuffled,
  splitAt,
  concat,
  concatMany,
  reverseConcat,
  flat,
  map,
  zip,
  zipBy,
  mapWithIndex,
  fromArray,
  toArray,
  reverse,
  mapReverse,
  forEach,
  forEachWithIndex,
  reduce,
  reduceWithIndex,
  reduceReverse,
  mapReverse2,
  forEach2,
  reduce2,
  reduceReverse2,
  every,
  some,
  every2,
  some2,
  compareLength,
  compare,
  equal,
  has,
  filter,
  filterWithIndex,
  filterMap,
  partition,
  unzip,
  getAssoc,
  hasAssoc,
  removeAssoc,
  setAssoc,
  sort,
  empty,
  singleton,
  repeat,
  range,
  initialize,
  cons,
  take,
  takeWhile,
  drop,
  dropWhile,
  initial,
  last,
  getAt,
  insertAt,
  updateAt,
  removeAt,
  sortBy,
  isEmpty,
  any,
  all,
  count,
  uniqueBy,
  find,
  findIndex,
  includes,
  minimumBy,
  maximumBy,
  minimum,
  maximum,
  extent,
  sum,
  flatMap,
  fold,
  foldRight,
  append,
  map2,
  map3,
  splitWhen,
  intersperse,
  chunksOf,
  sliding,
  groupWhile,
  join,
  groupBy,
  L,
  listToOption,
  foldLeft0,
  foldRight0,
  transpose,
  zipWith,
  combinationIf2,
  combination2,
  unfold,
}
/* TableclothList Not a pure module */
