// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Int from "@rescript/core/src/Core__Int.mjs";
import * as TableclothInt from "./Tablecloth/TableclothInt.mjs";

var Constants = Core__Int.Constants;

var range = Core__Int.range;

var rangeWithOptions = Core__Int.rangeWithOptions;

var zero = TableclothInt.zero;

var one = TableclothInt.one;

var maximumValue = TableclothInt.maximumValue;

var minimumValue = TableclothInt.minimumValue;

var fromString = TableclothInt.fromString;

var add = TableclothInt.add;

var subtract = TableclothInt.subtract;

var multiply = TableclothInt.multiply;

var divide = TableclothInt.divide;

var divideFloat = TableclothInt.divideFloat;

var power = TableclothInt.power;

var negate = TableclothInt.negate;

var absolute = TableclothInt.absolute;

var modulo = TableclothInt.modulo;

var remainder = TableclothInt.remainder;

var maximum = TableclothInt.maximum;

var minimum = TableclothInt.minimum;

var isEven = TableclothInt.isEven;

var isOdd = TableclothInt.isOdd;

var clamp = TableclothInt.clamp;

var inRange = TableclothInt.inRange;

var toFloat = TableclothInt.toFloat;

var toString = TableclothInt.toString;

var equal = TableclothInt.equal;

var compare = TableclothInt.compare;

var comparator = TableclothInt.comparator;

export {
  Constants ,
  range ,
  rangeWithOptions ,
  zero ,
  one ,
  maximumValue ,
  minimumValue ,
  fromString ,
  add ,
  subtract ,
  multiply ,
  divide ,
  divideFloat ,
  power ,
  negate ,
  absolute ,
  modulo ,
  remainder ,
  maximum ,
  minimum ,
  isEven ,
  isOdd ,
  clamp ,
  inRange ,
  toFloat ,
  toString ,
  equal ,
  compare ,
  comparator ,
}
/* TableclothInt Not a pure module */
