// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as TableclothFun from "./Tablecloth/TableclothFun.mjs";

function id(a) {
  return a;
}

function eq(x, y) {
  return x === y;
}

function $$const(a, param) {
  return a;
}

function on(b, u, x, y) {
  return Curry._2(b, Curry._1(u, x), Curry._1(u, y));
}

function applyWhen(condition, f, x) {
  if (condition) {
    return Curry._1(f, x);
  } else {
    return x;
  }
}

function composeU(f, g, x) {
  return Curry._1(g, Curry._1(f, x));
}

function compose(f, g, x) {
  return Curry._1(g, Curry._1(f, x));
}

function composeRight(f, g, x) {
  return Curry._1(f, Curry._1(g, x));
}

function compose3(f, g, h, x) {
  return Curry._1(h, Curry._1(g, Curry._1(f, x)));
}

function compose4(f, g, h, i, x) {
  return Curry._1(i, Curry._1(h, Curry._1(g, Curry._1(f, x))));
}

var complement = TableclothFun.negate;

export {
  id ,
  eq ,
  $$const ,
  complement ,
  on ,
  applyWhen ,
  composeU ,
  compose ,
  composeRight ,
  compose3 ,
  compose4 ,
}
/* No side effect */
