// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__String from "@rescript/core/src/Core__String.mjs";

function words(__x) {
  return __x.split(" ");
}

var equal = Core__String.equal;

var compare = Core__String.compare;

var indexOfOpt = Core__String.indexOfOpt;

var lastIndexOfOpt = Core__String.lastIndexOfOpt;

var searchOpt = Core__String.searchOpt;

export {
  equal ,
  compare ,
  indexOfOpt ,
  lastIndexOfOpt ,
  searchOpt ,
  words ,
}
/* No side effect */
