// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.mjs";
import * as Stdlib__Option_Ext from "./Stdlib__Option_Ext.mjs";

var filter = Core__Option.filter;

var forEach = Core__Option.forEach;

var getExn = Core__Option.getExn;

var mapOr = Core__Option.mapOr;

var mapWithDefault = Core__Option.mapWithDefault;

var map = Core__Option.map;

var flatMap = Core__Option.flatMap;

var getOr = Core__Option.getOr;

var getWithDefault = Core__Option.getWithDefault;

var orElse = Core__Option.orElse;

var isSome = Core__Option.isSome;

var isNone = Core__Option.isNone;

var equal = Core__Option.equal;

var compare = Core__Option.compare;

var getExnWithMessage = Stdlib__Option_Ext.getExnWithMessage;

var optionOr = Stdlib__Option_Ext.optionOr;

var fromMaybe = Stdlib__Option_Ext.fromMaybe;

var A = Stdlib__Option_Ext.A;

var arrayToMayBe = Stdlib__Option_Ext.arrayToMayBe;

var L = Stdlib__Option_Ext.L;

var listToMayBe = Stdlib__Option_Ext.listToMayBe;

export {
  filter ,
  forEach ,
  getExn ,
  mapOr ,
  mapWithDefault ,
  map ,
  flatMap ,
  getOr ,
  getWithDefault ,
  orElse ,
  isSome ,
  isNone ,
  equal ,
  compare ,
  getExnWithMessage ,
  optionOr ,
  fromMaybe ,
  A ,
  arrayToMayBe ,
  L ,
  listToMayBe ,
}
/* No side effect */
