// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "rescript/lib/es6/Stdlib_Option.js";
import * as TableclothOption from "./Tablecloth/TableclothOption.res.mjs";
import * as Stdlib__Option_Ext from "./Stdlib__Option_Ext.res.mjs";

let filter = Stdlib_Option.filter;

let forEach = Stdlib_Option.forEach;

let getExn = Stdlib_Option.getExn;

let getOrThrow = Stdlib_Option.getOrThrow;

let mapOr = Stdlib_Option.mapOr;

let mapWithDefault = Stdlib_Option.mapWithDefault;

let map = Stdlib_Option.map;

let flatMap = Stdlib_Option.flatMap;

let getOr = Stdlib_Option.getOr;

let getWithDefault = Stdlib_Option.getWithDefault;

let orElse = Stdlib_Option.orElse;

let isSome = Stdlib_Option.isSome;

let isNone = Stdlib_Option.isNone;

let equal = Stdlib_Option.equal;

let compare = Stdlib_Option.compare;

let all = Stdlib_Option.all;

let all2 = Stdlib_Option.all2;

let all3 = Stdlib_Option.all3;

let all4 = Stdlib_Option.all4;

let all5 = Stdlib_Option.all5;

let all6 = Stdlib_Option.all6;

let and_ = TableclothOption.and_;

let or_ = TableclothOption.or_;

let both = TableclothOption.both;

let flatten = TableclothOption.flatten;

let map2 = TableclothOption.map2;

let andThen = TableclothOption.andThen;

let unwrap = TableclothOption.unwrap;

let unwrapUnsafe = TableclothOption.unwrapUnsafe;

let tap = TableclothOption.tap;

let toArray = TableclothOption.toArray;

let toList = TableclothOption.toList;

let getExnWithMessage = Stdlib__Option_Ext.getExnWithMessage;

let fromMaybe = Stdlib__Option_Ext.fromMaybe;

let A = Stdlib__Option_Ext.A;

let arrayToMayBe = Stdlib__Option_Ext.arrayToMayBe;

let L = Stdlib__Option_Ext.L;

let listToMayBe = Stdlib__Option_Ext.listToMayBe;

export {
  filter,
  forEach,
  getExn,
  getOrThrow,
  mapOr,
  mapWithDefault,
  map,
  flatMap,
  getOr,
  getWithDefault,
  orElse,
  isSome,
  isNone,
  equal,
  compare,
  all,
  all2,
  all3,
  all4,
  all5,
  all6,
  and_,
  or_,
  both,
  flatten,
  map2,
  andThen,
  unwrap,
  unwrapUnsafe,
  tap,
  toArray,
  toList,
  getExnWithMessage,
  fromMaybe,
  A,
  arrayToMayBe,
  L,
  listToMayBe,
}
/* Stdlib__Option_Ext Not a pure module */
