// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/rescript-jest/src/jest.res.mjs";
import * as Stdlib__Set_Ext from "../src/Stdlib__Set_Ext.res.mjs";
import * as Stdlib__Array_Ext from "../src/Stdlib__Array_Ext.res.mjs";

Jest.describe("ArrayInt", () => {
  let si = Stdlib__Set_Ext.Value.$$Array.Int.make();
  beforeEach(() => {
    Stdlib__Set_Ext.Value.$$Array.Int.clear(si);
    Stdlib__Set_Ext.Value.$$Array.Int.add(si, [
      1,
      2,
      3
    ]);
    Stdlib__Set_Ext.Value.$$Array.Int.add(si, [
      4,
      5,
      6
    ]);
    Stdlib__Set_Ext.Value.$$Array.Int.add(si, [
      7,
      8,
      9
    ]);
  });
  Jest.test("clear all values", () => {
    Stdlib__Set_Ext.Value.$$Array.Int.clear(si);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Int.size(si)), 0);
  });
  Jest.test("forEach", () => {
    let values = [];
    Stdlib__Set_Ext.Value.$$Array.Int.forEach(si, v => {
      values.push(v);
    });
    return Jest.Expect.toEqual(Jest.Expect.expect(values), [
      [
        1,
        2,
        3
      ],
      [
        4,
        5,
        6
      ],
      [
        7,
        8,
        9
      ]
    ]);
  });
  Jest.test("has value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Int.has(si, [
    1,
    2,
    3
  ])), true));
  Jest.test("delete value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Int.$$delete(si, [
    1,
    2,
    3
  ])), true));
  Jest.test("fromArray", () => {
    let arr = [
      [
        1,
        2,
        3
      ],
      [
        4,
        5,
        6
      ]
    ];
    let si = Stdlib__Set_Ext.Value.$$Array.Int.fromArray(arr);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Int.size(si)), 2);
  });
  Jest.test("fromIterator", () => {
    let iter = Stdlib__Array_Ext.valuesIter([
      [
        1,
        2,
        3
      ],
      [
        4,
        5,
        6
      ]
    ]);
    let si = Stdlib__Set_Ext.Value.$$Array.Int.fromIterator(iter);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Int.size(si)), 2);
  });
  Jest.test("values", () => {
    let values = Stdlib__Set_Ext.Value.$$Array.Int.values(si).toArray();
    return Jest.Expect.toEqual(Jest.Expect.expect(values), [
      [
        1,
        2,
        3
      ],
      [
        4,
        5,
        6
      ],
      [
        7,
        8,
        9
      ]
    ]);
  });
  Jest.test("difference", () => {
    let si2 = Stdlib__Set_Ext.Value.$$Array.Int.make();
    Stdlib__Set_Ext.Value.$$Array.Int.add(si2, [
      4,
      5,
      6
    ]);
    let diff = Stdlib__Set_Ext.Value.$$Array.Int.difference(si, si2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Int.values(diff).toArray()), [
      [
        1,
        2,
        3
      ],
      [
        7,
        8,
        9
      ]
    ]);
  });
  Jest.test("intersection", () => {
    let si2 = Stdlib__Set_Ext.Value.$$Array.Int.make();
    Stdlib__Set_Ext.Value.$$Array.Int.add(si2, [
      4,
      5,
      6
    ]);
    let inter = Stdlib__Set_Ext.Value.$$Array.Int.intersection(si, si2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Int.values(inter).toArray()), [[
        4,
        5,
        6
      ]]);
  });
  Jest.test("union", () => {
    let si2 = Stdlib__Set_Ext.Value.$$Array.Int.make();
    Stdlib__Set_Ext.Value.$$Array.Int.add(si2, [
      10,
      11,
      12
    ]);
    let union = Stdlib__Set_Ext.Value.$$Array.Int.union(si, si2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Int.values(union).toArray()), [
      [
        1,
        2,
        3
      ],
      [
        4,
        5,
        6
      ],
      [
        7,
        8,
        9
      ],
      [
        10,
        11,
        12
      ]
    ]);
  });
  Jest.test("symmetricDifference", () => {
    let si2 = Stdlib__Set_Ext.Value.$$Array.Int.make();
    Stdlib__Set_Ext.Value.$$Array.Int.add(si2, [
      4,
      5,
      6
    ]);
    Stdlib__Set_Ext.Value.$$Array.Int.add(si2, [
      10,
      11,
      12
    ]);
    let symDiff = Stdlib__Set_Ext.Value.$$Array.Int.symmetricDifference(si, si2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Int.values(symDiff).toArray()), [
      [
        1,
        2,
        3
      ],
      [
        7,
        8,
        9
      ],
      [
        10,
        11,
        12
      ]
    ]);
  });
  Jest.test("isSubsetOf", () => {
    let si2 = Stdlib__Set_Ext.Value.$$Array.Int.make();
    Stdlib__Set_Ext.Value.$$Array.Int.add(si2, [
      1,
      2,
      3
    ]);
    Stdlib__Set_Ext.Value.$$Array.Int.add(si2, [
      4,
      5,
      6
    ]);
    Stdlib__Set_Ext.Value.$$Array.Int.add(si2, [
      7,
      8,
      9
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Int.isSubsetOf(si, si2)), true);
  });
  Jest.test("isSupersetOf", () => {
    let si2 = Stdlib__Set_Ext.Value.$$Array.Int.make();
    Stdlib__Set_Ext.Value.$$Array.Int.add(si2, [
      1,
      2,
      3
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Int.isSupersetOf(si, si2)), true);
  });
  Jest.test("isDisjointFrom", () => {
    let si2 = Stdlib__Set_Ext.Value.$$Array.Int.make();
    Stdlib__Set_Ext.Value.$$Array.Int.add(si2, [
      10,
      11,
      12
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Int.isDisjointFrom(si, si2)), true);
  });
});

Jest.describe("ArrayString", () => {
  let ss = Stdlib__Set_Ext.Value.$$Array.$$String.make();
  beforeEach(() => {
    Stdlib__Set_Ext.Value.$$Array.$$String.clear(ss);
    Stdlib__Set_Ext.Value.$$Array.$$String.add(ss, [
      "a",
      "b",
      "c"
    ]);
    Stdlib__Set_Ext.Value.$$Array.$$String.add(ss, [
      "d",
      "e",
      "f"
    ]);
    Stdlib__Set_Ext.Value.$$Array.$$String.add(ss, [
      "g",
      "h",
      "i"
    ]);
  });
  Jest.test("clear all values", () => {
    Stdlib__Set_Ext.Value.$$Array.$$String.clear(ss);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.$$String.size(ss)), 0);
  });
  Jest.test("forEach", () => {
    let values = [];
    Stdlib__Set_Ext.Value.$$Array.$$String.forEach(ss, v => {
      values.push(v);
    });
    return Jest.Expect.toEqual(Jest.Expect.expect(values), [
      [
        "a",
        "b",
        "c"
      ],
      [
        "d",
        "e",
        "f"
      ],
      [
        "g",
        "h",
        "i"
      ]
    ]);
  });
  Jest.test("has value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.$$String.has(ss, [
    "a",
    "b",
    "c"
  ])), true));
  Jest.test("delete value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.$$String.$$delete(ss, [
    "a",
    "b",
    "c"
  ])), true));
  Jest.test("fromArray", () => {
    let arr = [
      [
        "a",
        "b",
        "c"
      ],
      [
        "d",
        "e",
        "f"
      ]
    ];
    let ss = Stdlib__Set_Ext.Value.$$Array.$$String.fromArray(arr);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.$$String.size(ss)), 2);
  });
  Jest.test("fromIterator", () => {
    let iter = Stdlib__Array_Ext.valuesIter([
      [
        "a",
        "b",
        "c"
      ],
      [
        "d",
        "e",
        "f"
      ]
    ]);
    let ss = Stdlib__Set_Ext.Value.$$Array.$$String.fromIterator(iter);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.$$String.size(ss)), 2);
  });
  Jest.test("values", () => {
    let values = Stdlib__Set_Ext.Value.$$Array.$$String.values(ss).toArray();
    return Jest.Expect.toEqual(Jest.Expect.expect(values), [
      [
        "a",
        "b",
        "c"
      ],
      [
        "d",
        "e",
        "f"
      ],
      [
        "g",
        "h",
        "i"
      ]
    ]);
  });
  Jest.test("difference", () => {
    let ss2 = Stdlib__Set_Ext.Value.$$Array.$$String.make();
    Stdlib__Set_Ext.Value.$$Array.$$String.add(ss2, [
      "d",
      "e",
      "f"
    ]);
    let diff = Stdlib__Set_Ext.Value.$$Array.$$String.difference(ss, ss2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.$$String.values(diff).toArray()), [
      [
        "a",
        "b",
        "c"
      ],
      [
        "g",
        "h",
        "i"
      ]
    ]);
  });
  Jest.test("intersection", () => {
    let ss2 = Stdlib__Set_Ext.Value.$$Array.$$String.make();
    Stdlib__Set_Ext.Value.$$Array.$$String.add(ss2, [
      "d",
      "e",
      "f"
    ]);
    let inter = Stdlib__Set_Ext.Value.$$Array.$$String.intersection(ss, ss2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.$$String.values(inter).toArray()), [[
        "d",
        "e",
        "f"
      ]]);
  });
  Jest.test("union", () => {
    let ss2 = Stdlib__Set_Ext.Value.$$Array.$$String.make();
    Stdlib__Set_Ext.Value.$$Array.$$String.add(ss2, [
      "j",
      "k",
      "l"
    ]);
    let union = Stdlib__Set_Ext.Value.$$Array.$$String.union(ss, ss2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.$$String.values(union).toArray()), [
      [
        "a",
        "b",
        "c"
      ],
      [
        "d",
        "e",
        "f"
      ],
      [
        "g",
        "h",
        "i"
      ],
      [
        "j",
        "k",
        "l"
      ]
    ]);
  });
  Jest.test("symmetricDifference", () => {
    let ss2 = Stdlib__Set_Ext.Value.$$Array.$$String.make();
    Stdlib__Set_Ext.Value.$$Array.$$String.add(ss2, [
      "d",
      "e",
      "f"
    ]);
    Stdlib__Set_Ext.Value.$$Array.$$String.add(ss2, [
      "j",
      "k",
      "l"
    ]);
    let symDiff = Stdlib__Set_Ext.Value.$$Array.$$String.symmetricDifference(ss, ss2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.$$String.values(symDiff).toArray()), [
      [
        "a",
        "b",
        "c"
      ],
      [
        "g",
        "h",
        "i"
      ],
      [
        "j",
        "k",
        "l"
      ]
    ]);
  });
  Jest.test("isSubsetOf", () => {
    let ss2 = Stdlib__Set_Ext.Value.$$Array.$$String.make();
    Stdlib__Set_Ext.Value.$$Array.$$String.add(ss2, [
      "a",
      "b",
      "c"
    ]);
    Stdlib__Set_Ext.Value.$$Array.$$String.add(ss2, [
      "d",
      "e",
      "f"
    ]);
    Stdlib__Set_Ext.Value.$$Array.$$String.add(ss2, [
      "g",
      "h",
      "i"
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.$$String.isSubsetOf(ss, ss2)), true);
  });
  Jest.test("isSupersetOf", () => {
    let ss2 = Stdlib__Set_Ext.Value.$$Array.$$String.make();
    Stdlib__Set_Ext.Value.$$Array.$$String.add(ss2, [
      "a",
      "b",
      "c"
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.$$String.isSupersetOf(ss, ss2)), true);
  });
  Jest.test("isDisjointFrom", () => {
    let ss2 = Stdlib__Set_Ext.Value.$$Array.$$String.make();
    Stdlib__Set_Ext.Value.$$Array.$$String.add(ss2, [
      "j",
      "k",
      "l"
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.$$String.isDisjointFrom(ss, ss2)), true);
  });
});

Jest.describe("ArrayFloat", () => {
  let sf = Stdlib__Set_Ext.Value.$$Array.Float.make();
  beforeEach(() => {
    Stdlib__Set_Ext.Value.$$Array.Float.clear(sf);
    Stdlib__Set_Ext.Value.$$Array.Float.add(sf, [
      1.1,
      2.2,
      3.3
    ]);
    Stdlib__Set_Ext.Value.$$Array.Float.add(sf, [
      4.4,
      5.5,
      6.6
    ]);
    Stdlib__Set_Ext.Value.$$Array.Float.add(sf, [
      7.7,
      8.8,
      9.9
    ]);
  });
  Jest.test("clear all values", () => {
    Stdlib__Set_Ext.Value.$$Array.Float.clear(sf);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Float.size(sf)), 0);
  });
  Jest.test("forEach", () => {
    let values = [];
    Stdlib__Set_Ext.Value.$$Array.Float.forEach(sf, v => {
      values.push(v);
    });
    return Jest.Expect.toEqual(Jest.Expect.expect(values), [
      [
        1.1,
        2.2,
        3.3
      ],
      [
        4.4,
        5.5,
        6.6
      ],
      [
        7.7,
        8.8,
        9.9
      ]
    ]);
  });
  Jest.test("has value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Float.has(sf, [
    1.1,
    2.2,
    3.3
  ])), true));
  Jest.test("delete value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Float.$$delete(sf, [
    1.1,
    2.2,
    3.3
  ])), true));
  Jest.test("fromArray", () => {
    let arr = [
      [
        1.1,
        2.2,
        3.3
      ],
      [
        4.4,
        5.5,
        6.6
      ]
    ];
    let sf = Stdlib__Set_Ext.Value.$$Array.Float.fromArray(arr);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Float.size(sf)), 2);
  });
  Jest.test("fromIterator", () => {
    let iter = Stdlib__Array_Ext.valuesIter([
      [
        1.1,
        2.2,
        3.3
      ],
      [
        4.4,
        5.5,
        6.6
      ]
    ]);
    let sf = Stdlib__Set_Ext.Value.$$Array.Float.fromIterator(iter);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Float.size(sf)), 2);
  });
  Jest.test("values", () => {
    let values = Stdlib__Set_Ext.Value.$$Array.Float.values(sf).toArray();
    return Jest.Expect.toEqual(Jest.Expect.expect(values), [
      [
        1.1,
        2.2,
        3.3
      ],
      [
        4.4,
        5.5,
        6.6
      ],
      [
        7.7,
        8.8,
        9.9
      ]
    ]);
  });
  Jest.test("difference", () => {
    let sf2 = Stdlib__Set_Ext.Value.$$Array.Float.make();
    Stdlib__Set_Ext.Value.$$Array.Float.add(sf2, [
      4.4,
      5.5,
      6.6
    ]);
    let diff = Stdlib__Set_Ext.Value.$$Array.Float.difference(sf, sf2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Float.values(diff).toArray()), [
      [
        1.1,
        2.2,
        3.3
      ],
      [
        7.7,
        8.8,
        9.9
      ]
    ]);
  });
  Jest.test("intersection", () => {
    let sf2 = Stdlib__Set_Ext.Value.$$Array.Float.make();
    Stdlib__Set_Ext.Value.$$Array.Float.add(sf2, [
      4.4,
      5.5,
      6.6
    ]);
    let inter = Stdlib__Set_Ext.Value.$$Array.Float.intersection(sf, sf2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Float.values(inter).toArray()), [[
        4.4,
        5.5,
        6.6
      ]]);
  });
  Jest.test("union", () => {
    let sf2 = Stdlib__Set_Ext.Value.$$Array.Float.make();
    Stdlib__Set_Ext.Value.$$Array.Float.add(sf2, [
      10.1,
      11.2,
      12.3
    ]);
    let union = Stdlib__Set_Ext.Value.$$Array.Float.union(sf, sf2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Float.values(union).toArray()), [
      [
        1.1,
        2.2,
        3.3
      ],
      [
        4.4,
        5.5,
        6.6
      ],
      [
        7.7,
        8.8,
        9.9
      ],
      [
        10.1,
        11.2,
        12.3
      ]
    ]);
  });
  Jest.test("symmetricDifference", () => {
    let sf2 = Stdlib__Set_Ext.Value.$$Array.Float.make();
    Stdlib__Set_Ext.Value.$$Array.Float.add(sf2, [
      4.4,
      5.5,
      6.6
    ]);
    Stdlib__Set_Ext.Value.$$Array.Float.add(sf2, [
      10.1,
      11.2,
      12.3
    ]);
    let symDiff = Stdlib__Set_Ext.Value.$$Array.Float.symmetricDifference(sf, sf2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Float.values(symDiff).toArray()), [
      [
        1.1,
        2.2,
        3.3
      ],
      [
        7.7,
        8.8,
        9.9
      ],
      [
        10.1,
        11.2,
        12.3
      ]
    ]);
  });
  Jest.test("isSubsetOf", () => {
    let sf2 = Stdlib__Set_Ext.Value.$$Array.Float.make();
    Stdlib__Set_Ext.Value.$$Array.Float.add(sf2, [
      1.1,
      2.2,
      3.3
    ]);
    Stdlib__Set_Ext.Value.$$Array.Float.add(sf2, [
      4.4,
      5.5,
      6.6
    ]);
    Stdlib__Set_Ext.Value.$$Array.Float.add(sf2, [
      7.7,
      8.8,
      9.9
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Float.isSubsetOf(sf, sf2)), true);
  });
  Jest.test("isSupersetOf", () => {
    let sf2 = Stdlib__Set_Ext.Value.$$Array.Float.make();
    Stdlib__Set_Ext.Value.$$Array.Float.add(sf2, [
      1.1,
      2.2,
      3.3
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Float.isSupersetOf(sf, sf2)), true);
  });
  Jest.test("isDisjointFrom", () => {
    let sf2 = Stdlib__Set_Ext.Value.$$Array.Float.make();
    Stdlib__Set_Ext.Value.$$Array.Float.add(sf2, [
      10.1,
      11.2,
      12.3
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Float.isDisjointFrom(sf, sf2)), true);
  });
});

Jest.describe("SetTuple2IntString", () => {
  let stis = Stdlib__Set_Ext.Value.Tuple2.IntString.make();
  beforeEach(() => {
    Stdlib__Set_Ext.Value.Tuple2.IntString.clear(stis);
    Stdlib__Set_Ext.Value.Tuple2.IntString.add(stis, [
      1,
      "one"
    ]);
    Stdlib__Set_Ext.Value.Tuple2.IntString.add(stis, [
      2,
      "two"
    ]);
  });
  Jest.test("clear all values", () => {
    Stdlib__Set_Ext.Value.Tuple2.IntString.clear(stis);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.IntString.size(stis)), 0);
  });
  Jest.test("forEach", () => {
    let values = [];
    Stdlib__Set_Ext.Value.Tuple2.IntString.forEach(stis, v => {
      values.push(v);
    });
    return Jest.Expect.toEqual(Jest.Expect.expect(values), [
      [
        1,
        "one"
      ],
      [
        2,
        "two"
      ]
    ]);
  });
  Jest.test("has value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.IntString.has(stis, [
    1,
    "one"
  ])), true));
  Jest.test("delete value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.IntString.$$delete(stis, [
    1,
    "one"
  ])), true));
  Jest.test("fromArray", () => {
    let arr = [
      [
        1,
        "one"
      ],
      [
        2,
        "two"
      ]
    ];
    let stis = Stdlib__Set_Ext.Value.Tuple2.IntString.fromArray(arr);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.IntString.size(stis)), 2);
  });
  Jest.test("fromIterator", () => {
    let iter = Stdlib__Array_Ext.valuesIter([
      [
        1,
        "one"
      ],
      [
        2,
        "two"
      ]
    ]);
    let stis = Stdlib__Set_Ext.Value.Tuple2.IntString.fromIterator(iter);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.IntString.size(stis)), 2);
  });
  Jest.test("values", () => {
    let values = Stdlib__Set_Ext.Value.Tuple2.IntString.values(stis).toArray();
    return Jest.Expect.toEqual(Jest.Expect.expect(values), [
      [
        1,
        "one"
      ],
      [
        2,
        "two"
      ]
    ]);
  });
  Jest.test("difference", () => {
    let stis2 = Stdlib__Set_Ext.Value.Tuple2.IntString.make();
    Stdlib__Set_Ext.Value.Tuple2.IntString.add(stis2, [
      2,
      "two"
    ]);
    let diff = Stdlib__Set_Ext.Value.Tuple2.IntString.difference(stis, stis2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.IntString.values(diff).toArray()), [[
        1,
        "one"
      ]]);
  });
  Jest.test("intersection", () => {
    let stis2 = Stdlib__Set_Ext.Value.Tuple2.IntString.make();
    Stdlib__Set_Ext.Value.Tuple2.IntString.add(stis2, [
      2,
      "two"
    ]);
    let inter = Stdlib__Set_Ext.Value.Tuple2.IntString.intersection(stis, stis2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.IntString.values(inter).toArray()), [[
        2,
        "two"
      ]]);
  });
  Jest.test("union", () => {
    let stis2 = Stdlib__Set_Ext.Value.Tuple2.IntString.make();
    Stdlib__Set_Ext.Value.Tuple2.IntString.add(stis2, [
      3,
      "three"
    ]);
    let union = Stdlib__Set_Ext.Value.Tuple2.IntString.union(stis, stis2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.IntString.values(union).toArray()), [
      [
        1,
        "one"
      ],
      [
        2,
        "two"
      ],
      [
        3,
        "three"
      ]
    ]);
  });
  Jest.test("symmetricDifference", () => {
    let stis2 = Stdlib__Set_Ext.Value.Tuple2.IntString.make();
    Stdlib__Set_Ext.Value.Tuple2.IntString.add(stis2, [
      2,
      "two"
    ]);
    Stdlib__Set_Ext.Value.Tuple2.IntString.add(stis2, [
      3,
      "three"
    ]);
    let symDiff = Stdlib__Set_Ext.Value.Tuple2.IntString.symmetricDifference(stis, stis2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.IntString.values(symDiff).toArray()), [
      [
        1,
        "one"
      ],
      [
        3,
        "three"
      ]
    ]);
  });
  Jest.test("isSubsetOf", () => {
    let stis2 = Stdlib__Set_Ext.Value.Tuple2.IntString.make();
    Stdlib__Set_Ext.Value.Tuple2.IntString.add(stis2, [
      1,
      "one"
    ]);
    Stdlib__Set_Ext.Value.Tuple2.IntString.add(stis2, [
      2,
      "two"
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.IntString.isSubsetOf(stis, stis2)), true);
  });
  Jest.test("isSupersetOf", () => {
    let stis2 = Stdlib__Set_Ext.Value.Tuple2.IntString.make();
    Stdlib__Set_Ext.Value.Tuple2.IntString.add(stis2, [
      1,
      "one"
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.IntString.isSupersetOf(stis, stis2)), true);
  });
  Jest.test("isDisjointFrom", () => {
    let stis2 = Stdlib__Set_Ext.Value.Tuple2.IntString.make();
    Stdlib__Set_Ext.Value.Tuple2.IntString.add(stis2, [
      3,
      "three"
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.IntString.isDisjointFrom(stis, stis2)), true);
  });
});

Jest.describe("SetTuple2FloatFloat", () => {
  let stff = Stdlib__Set_Ext.Value.Tuple2.FloatFloat.make();
  beforeEach(() => {
    Stdlib__Set_Ext.Value.Tuple2.FloatFloat.clear(stff);
    Stdlib__Set_Ext.Value.Tuple2.FloatFloat.add(stff, [
      1.1,
      2.2
    ]);
    Stdlib__Set_Ext.Value.Tuple2.FloatFloat.add(stff, [
      3.3,
      4.4
    ]);
  });
  Jest.test("clear all values", () => {
    Stdlib__Set_Ext.Value.Tuple2.FloatFloat.clear(stff);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.FloatFloat.size(stff)), 0);
  });
  Jest.test("forEach", () => {
    let values = [];
    Stdlib__Set_Ext.Value.Tuple2.FloatFloat.forEach(stff, v => {
      values.push(v);
    });
    return Jest.Expect.toEqual(Jest.Expect.expect(values), [
      [
        1.1,
        2.2
      ],
      [
        3.3,
        4.4
      ]
    ]);
  });
  Jest.test("has value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.FloatFloat.has(stff, [
    1.1,
    2.2
  ])), true));
  Jest.test("delete value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.FloatFloat.$$delete(stff, [
    1.1,
    2.2
  ])), true));
  Jest.test("fromArray", () => {
    let arr = [
      [
        1.1,
        2.2
      ],
      [
        3.3,
        4.4
      ]
    ];
    let stff = Stdlib__Set_Ext.Value.Tuple2.FloatFloat.fromArray(arr);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.FloatFloat.size(stff)), 2);
  });
  Jest.test("fromIterator", () => {
    let iter = Stdlib__Array_Ext.valuesIter([
      [
        1.1,
        2.2
      ],
      [
        3.3,
        4.4
      ]
    ]);
    let stff = Stdlib__Set_Ext.Value.Tuple2.FloatFloat.fromIterator(iter);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.FloatFloat.size(stff)), 2);
  });
  Jest.test("values", () => {
    let values = Stdlib__Set_Ext.Value.Tuple2.FloatFloat.values(stff).toArray();
    return Jest.Expect.toEqual(Jest.Expect.expect(values), [
      [
        1.1,
        2.2
      ],
      [
        3.3,
        4.4
      ]
    ]);
  });
  Jest.test("difference", () => {
    let stff2 = Stdlib__Set_Ext.Value.Tuple2.FloatFloat.make();
    Stdlib__Set_Ext.Value.Tuple2.FloatFloat.add(stff2, [
      3.3,
      4.4
    ]);
    let diff = Stdlib__Set_Ext.Value.Tuple2.FloatFloat.difference(stff, stff2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.FloatFloat.values(diff).toArray()), [[
        1.1,
        2.2
      ]]);
  });
  Jest.test("intersection", () => {
    let stff2 = Stdlib__Set_Ext.Value.Tuple2.FloatFloat.make();
    Stdlib__Set_Ext.Value.Tuple2.FloatFloat.add(stff2, [
      3.3,
      4.4
    ]);
    let inter = Stdlib__Set_Ext.Value.Tuple2.FloatFloat.intersection(stff, stff2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.FloatFloat.values(inter).toArray()), [[
        3.3,
        4.4
      ]]);
  });
  Jest.test("union", () => {
    let stff2 = Stdlib__Set_Ext.Value.Tuple2.FloatFloat.make();
    Stdlib__Set_Ext.Value.Tuple2.FloatFloat.add(stff2, [
      5.5,
      6.6
    ]);
    let union = Stdlib__Set_Ext.Value.Tuple2.FloatFloat.union(stff, stff2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.FloatFloat.values(union).toArray()), [
      [
        1.1,
        2.2
      ],
      [
        3.3,
        4.4
      ],
      [
        5.5,
        6.6
      ]
    ]);
  });
  Jest.test("symmetricDifference", () => {
    let stff2 = Stdlib__Set_Ext.Value.Tuple2.FloatFloat.make();
    Stdlib__Set_Ext.Value.Tuple2.FloatFloat.add(stff2, [
      3.3,
      4.4
    ]);
    Stdlib__Set_Ext.Value.Tuple2.FloatFloat.add(stff2, [
      5.5,
      6.6
    ]);
    let symDiff = Stdlib__Set_Ext.Value.Tuple2.FloatFloat.symmetricDifference(stff, stff2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.FloatFloat.values(symDiff).toArray()), [
      [
        1.1,
        2.2
      ],
      [
        5.5,
        6.6
      ]
    ]);
  });
  Jest.test("isSubsetOf", () => {
    let stff2 = Stdlib__Set_Ext.Value.Tuple2.FloatFloat.make();
    Stdlib__Set_Ext.Value.Tuple2.FloatFloat.add(stff2, [
      1.1,
      2.2
    ]);
    Stdlib__Set_Ext.Value.Tuple2.FloatFloat.add(stff2, [
      3.3,
      4.4
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.FloatFloat.isSubsetOf(stff, stff2)), true);
  });
  Jest.test("isSupersetOf", () => {
    let stff2 = Stdlib__Set_Ext.Value.Tuple2.FloatFloat.make();
    Stdlib__Set_Ext.Value.Tuple2.FloatFloat.add(stff2, [
      1.1,
      2.2
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.FloatFloat.isSupersetOf(stff, stff2)), true);
  });
  Jest.test("isDisjointFrom", () => {
    let stff2 = Stdlib__Set_Ext.Value.Tuple2.FloatFloat.make();
    Stdlib__Set_Ext.Value.Tuple2.FloatFloat.add(stff2, [
      5.5,
      6.6
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.FloatFloat.isDisjointFrom(stff, stff2)), true);
  });
});

Jest.describe("SetTuple3IntIntInt", () => {
  let stiii = Stdlib__Set_Ext.Value.Tuple3.IntIntInt.make();
  beforeEach(() => {
    Stdlib__Set_Ext.Value.Tuple3.IntIntInt.clear(stiii);
    Stdlib__Set_Ext.Value.Tuple3.IntIntInt.add(stiii, [
      1,
      2,
      3
    ]);
    Stdlib__Set_Ext.Value.Tuple3.IntIntInt.add(stiii, [
      4,
      5,
      6
    ]);
  });
  Jest.test("clear all values", () => {
    Stdlib__Set_Ext.Value.Tuple3.IntIntInt.clear(stiii);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple3.IntIntInt.size(stiii)), 0);
  });
  Jest.test("forEach", () => {
    let values = [];
    Stdlib__Set_Ext.Value.Tuple3.IntIntInt.forEach(stiii, v => {
      values.push(v);
    });
    return Jest.Expect.toEqual(Jest.Expect.expect(values), [
      [
        1,
        2,
        3
      ],
      [
        4,
        5,
        6
      ]
    ]);
  });
  Jest.test("has value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple3.IntIntInt.has(stiii, [
    1,
    2,
    3
  ])), true));
  Jest.test("delete value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple3.IntIntInt.$$delete(stiii, [
    1,
    2,
    3
  ])), true));
  Jest.test("fromArray", () => {
    let arr = [
      [
        1,
        2,
        3
      ],
      [
        4,
        5,
        6
      ]
    ];
    let stiii = Stdlib__Set_Ext.Value.Tuple3.IntIntInt.fromArray(arr);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple3.IntIntInt.size(stiii)), 2);
  });
  Jest.test("fromIterator", () => {
    let iter = Stdlib__Array_Ext.valuesIter([
      [
        1,
        2,
        3
      ],
      [
        4,
        5,
        6
      ]
    ]);
    let stiii = Stdlib__Set_Ext.Value.Tuple3.IntIntInt.fromIterator(iter);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple3.IntIntInt.size(stiii)), 2);
  });
  Jest.test("values", () => {
    let values = Stdlib__Set_Ext.Value.Tuple3.IntIntInt.values(stiii).toArray();
    return Jest.Expect.toEqual(Jest.Expect.expect(values), [
      [
        1,
        2,
        3
      ],
      [
        4,
        5,
        6
      ]
    ]);
  });
  Jest.test("difference", () => {
    let stiii2 = Stdlib__Set_Ext.Value.Tuple3.IntIntInt.make();
    Stdlib__Set_Ext.Value.Tuple3.IntIntInt.add(stiii2, [
      4,
      5,
      6
    ]);
    let diff = Stdlib__Set_Ext.Value.Tuple3.IntIntInt.difference(stiii, stiii2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple3.IntIntInt.values(diff).toArray()), [[
        1,
        2,
        3
      ]]);
  });
  Jest.test("intersection", () => {
    let stiii2 = Stdlib__Set_Ext.Value.Tuple3.IntIntInt.make();
    Stdlib__Set_Ext.Value.Tuple3.IntIntInt.add(stiii2, [
      4,
      5,
      6
    ]);
    let inter = Stdlib__Set_Ext.Value.Tuple3.IntIntInt.intersection(stiii, stiii2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple3.IntIntInt.values(inter).toArray()), [[
        4,
        5,
        6
      ]]);
  });
  Jest.test("union", () => {
    let stiii2 = Stdlib__Set_Ext.Value.Tuple3.IntIntInt.make();
    Stdlib__Set_Ext.Value.Tuple3.IntIntInt.add(stiii2, [
      7,
      8,
      9
    ]);
    let union = Stdlib__Set_Ext.Value.Tuple3.IntIntInt.union(stiii, stiii2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple3.IntIntInt.values(union).toArray()), [
      [
        1,
        2,
        3
      ],
      [
        4,
        5,
        6
      ],
      [
        7,
        8,
        9
      ]
    ]);
  });
  Jest.test("symmetricDifference", () => {
    let stiii2 = Stdlib__Set_Ext.Value.Tuple3.IntIntInt.make();
    Stdlib__Set_Ext.Value.Tuple3.IntIntInt.add(stiii2, [
      4,
      5,
      6
    ]);
    Stdlib__Set_Ext.Value.Tuple3.IntIntInt.add(stiii2, [
      7,
      8,
      9
    ]);
    let symDiff = Stdlib__Set_Ext.Value.Tuple3.IntIntInt.symmetricDifference(stiii, stiii2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple3.IntIntInt.values(symDiff).toArray()), [
      [
        1,
        2,
        3
      ],
      [
        7,
        8,
        9
      ]
    ]);
  });
  Jest.test("isSubsetOf", () => {
    let stiii2 = Stdlib__Set_Ext.Value.Tuple3.IntIntInt.make();
    Stdlib__Set_Ext.Value.Tuple3.IntIntInt.add(stiii2, [
      1,
      2,
      3
    ]);
    Stdlib__Set_Ext.Value.Tuple3.IntIntInt.add(stiii2, [
      4,
      5,
      6
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple3.IntIntInt.isSubsetOf(stiii, stiii2)), true);
  });
  Jest.test("isSupersetOf", () => {
    let stiii2 = Stdlib__Set_Ext.Value.Tuple3.IntIntInt.make();
    Stdlib__Set_Ext.Value.Tuple3.IntIntInt.add(stiii2, [
      1,
      2,
      3
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple3.IntIntInt.isSupersetOf(stiii, stiii2)), true);
  });
  Jest.test("isDisjointFrom", () => {
    let stiii2 = Stdlib__Set_Ext.Value.Tuple3.IntIntInt.make();
    Stdlib__Set_Ext.Value.Tuple3.IntIntInt.add(stiii2, [
      7,
      8,
      9
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple3.IntIntInt.isDisjointFrom(stiii, stiii2)), true);
  });
});

let ArrayInt;

let ArrayString;

let ArrayFloat;

let SetTuple2IntString;

let SetTuple2FloatFloat;

let SetTuple3IntIntInt;

export {
  ArrayInt,
  ArrayString,
  ArrayFloat,
  SetTuple2IntString,
  SetTuple2FloatFloat,
  SetTuple3IntIntInt,
}
/*  Not a pure module */
