// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/rescript-jest/src/jest.res.mjs";
import * as Stdlib__Set_Ext from "../src/Stdlib__Set_Ext.res.mjs";
import * as Stdlib__Array_Ext from "../src/Stdlib__Array_Ext.res.mjs";

Jest.describe("PrimInt", () => {
  let s = Stdlib__Set_Ext.Value.Int.make();
  beforeEach(() => {
    Stdlib__Set_Ext.Value.Int.clear(s);
    Stdlib__Set_Ext.Value.Int.add(s, 1);
    Stdlib__Set_Ext.Value.Int.add(s, 2);
    Stdlib__Set_Ext.Value.Int.add(s, 3);
  });
  Jest.test("make creates empty set", () => {
    let newSet = Stdlib__Set_Ext.Value.Int.make();
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Int.size(newSet)), 0);
  });
  Jest.test("size returns correct count", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Int.size(s)), 3));
  Jest.test("add adds new value", () => {
    Stdlib__Set_Ext.Value.Int.add(s, 4);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Int.size(s)), 4);
  });
  Jest.test("add doesn't duplicate existing value", () => {
    Stdlib__Set_Ext.Value.Int.add(s, 1);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Int.size(s)), 3);
  });
  Jest.test("has returns true for existing value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Int.has(s, 2)), true));
  Jest.test("has returns false for missing value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Int.has(s, 99)), false));
  Jest.test("delete removes existing value", () => {
    let deleted = Stdlib__Set_Ext.Value.Int.$$delete(s, 1);
    return Jest.Expect.toEqual(Jest.Expect.expect([
      deleted,
      Stdlib__Set_Ext.Value.Int.has(s, 1)
    ]), [
      true,
      false
    ]);
  });
  Jest.test("delete returns false for missing value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Int.$$delete(s, 99)), false));
  Jest.test("clear removes all values", () => {
    Stdlib__Set_Ext.Value.Int.clear(s);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Int.size(s)), 0);
  });
  Jest.test("isEmpty returns false for non-empty set", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Int.isEmpty(s)), false));
  Jest.test("isEmpty returns true for empty set", () => {
    let emptySet = Stdlib__Set_Ext.Value.Int.make();
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Int.isEmpty(emptySet)), true);
  });
  Jest.test("fromArray creates set from array", () => {
    let arr = [
      5,
      6,
      7
    ];
    let newSet = Stdlib__Set_Ext.Value.Int.fromArray(arr);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Int.size(newSet)), 3);
  });
  Jest.test("fromIterator creates set from iterator", () => {
    let iter = Stdlib__Array_Ext.valuesIter([
      10,
      20,
      30
    ]);
    let newSet = Stdlib__Set_Ext.Value.Int.fromIterator(iter);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Int.size(newSet)), 3);
  });
  Jest.test("values returns iterator of values", () => {
    let values = Stdlib__Set_Ext.Value.Int.values(s).toArray();
    return Jest.Expect.toBe(Jest.Expect.expect(values.length), 3);
  });
  Jest.test("forEach iterates over values", () => {
    let values = [];
    Stdlib__Set_Ext.Value.Int.forEach(s, v => {
      values.push(v);
    });
    return Jest.Expect.toBe(Jest.Expect.expect(values.length), 3);
  });
  Jest.test("toArray converts set to array", () => {
    let arr = Stdlib__Set_Ext.Value.Int.toArray(s);
    return Jest.Expect.toBe(Jest.Expect.expect(arr.length), 3);
  });
  Jest.test("difference", () => {
    let s2 = Stdlib__Set_Ext.Value.Int.make();
    Stdlib__Set_Ext.Value.Int.add(s2, 2);
    let diff = Stdlib__Set_Ext.Value.Int.difference(s, s2);
    return Jest.Expect.toEqual(Jest.Expect.expect([
      Stdlib__Set_Ext.Value.Int.has(diff, 1),
      Stdlib__Set_Ext.Value.Int.has(diff, 2),
      Stdlib__Set_Ext.Value.Int.has(diff, 3)
    ]), [
      true,
      false,
      true
    ]);
  });
  Jest.test("intersection", () => {
    let s2 = Stdlib__Set_Ext.Value.Int.make();
    Stdlib__Set_Ext.Value.Int.add(s2, 2);
    Stdlib__Set_Ext.Value.Int.add(s2, 4);
    let inter = Stdlib__Set_Ext.Value.Int.intersection(s, s2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.Int.values(inter).toArray()), [2]);
  });
  Jest.test("union", () => {
    let s2 = Stdlib__Set_Ext.Value.Int.make();
    Stdlib__Set_Ext.Value.Int.add(s2, 4);
    Stdlib__Set_Ext.Value.Int.add(s2, 5);
    let union = Stdlib__Set_Ext.Value.Int.union(s, s2);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Int.size(union)), 5);
  });
  Jest.test("symmetricDifference", () => {
    let s2 = Stdlib__Set_Ext.Value.Int.make();
    Stdlib__Set_Ext.Value.Int.add(s2, 2);
    Stdlib__Set_Ext.Value.Int.add(s2, 4);
    let symDiff = Stdlib__Set_Ext.Value.Int.symmetricDifference(s, s2);
    return Jest.Expect.toEqual(Jest.Expect.expect([
      Stdlib__Set_Ext.Value.Int.has(symDiff, 1),
      Stdlib__Set_Ext.Value.Int.has(symDiff, 2),
      Stdlib__Set_Ext.Value.Int.has(symDiff, 3),
      Stdlib__Set_Ext.Value.Int.has(symDiff, 4)
    ]), [
      true,
      false,
      true,
      true
    ]);
  });
  Jest.test("isSubsetOf", () => {
    let s2 = Stdlib__Set_Ext.Value.Int.make();
    Stdlib__Set_Ext.Value.Int.add(s2, 1);
    Stdlib__Set_Ext.Value.Int.add(s2, 2);
    Stdlib__Set_Ext.Value.Int.add(s2, 3);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Int.isSubsetOf(s, s2)), true);
  });
  Jest.test("isSupersetOf", () => {
    let s2 = Stdlib__Set_Ext.Value.Int.make();
    Stdlib__Set_Ext.Value.Int.add(s2, 1);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Int.isSupersetOf(s, s2)), true);
  });
  Jest.test("isDisjointFrom", () => {
    let s2 = Stdlib__Set_Ext.Value.Int.make();
    Stdlib__Set_Ext.Value.Int.add(s2, 10);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Int.isDisjointFrom(s, s2)), true);
  });
  Jest.test("ignore discards the set", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Int.ignore(s)), undefined));
});

Jest.describe("PrimString", () => {
  let s = Stdlib__Set_Ext.Value.$$String.make();
  beforeEach(() => {
    Stdlib__Set_Ext.Value.$$String.clear(s);
    Stdlib__Set_Ext.Value.$$String.add(s, "a");
    Stdlib__Set_Ext.Value.$$String.add(s, "b");
    Stdlib__Set_Ext.Value.$$String.add(s, "c");
  });
  Jest.test("make creates empty set", () => {
    let newSet = Stdlib__Set_Ext.Value.$$String.make();
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$String.size(newSet)), 0);
  });
  Jest.test("size returns correct count", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$String.size(s)), 3));
  Jest.test("add adds new value", () => {
    Stdlib__Set_Ext.Value.$$String.add(s, "d");
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$String.size(s)), 4);
  });
  Jest.test("add doesn't duplicate existing value", () => {
    Stdlib__Set_Ext.Value.$$String.add(s, "a");
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$String.size(s)), 3);
  });
  Jest.test("has returns true for existing value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$String.has(s, "b")), true));
  Jest.test("has returns false for missing value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$String.has(s, "z")), false));
  Jest.test("delete removes existing value", () => {
    let deleted = Stdlib__Set_Ext.Value.$$String.$$delete(s, "a");
    return Jest.Expect.toEqual(Jest.Expect.expect([
      deleted,
      Stdlib__Set_Ext.Value.$$String.has(s, "a")
    ]), [
      true,
      false
    ]);
  });
  Jest.test("delete returns false for missing value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$String.$$delete(s, "z")), false));
  Jest.test("clear removes all values", () => {
    Stdlib__Set_Ext.Value.$$String.clear(s);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$String.size(s)), 0);
  });
  Jest.test("isEmpty returns false for non-empty set", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$String.isEmpty(s)), false));
  Jest.test("isEmpty returns true for empty set", () => {
    let emptySet = Stdlib__Set_Ext.Value.$$String.make();
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$String.isEmpty(emptySet)), true);
  });
  Jest.test("fromArray creates set from array", () => {
    let arr = [
      "x",
      "y",
      "z"
    ];
    let newSet = Stdlib__Set_Ext.Value.$$String.fromArray(arr);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$String.size(newSet)), 3);
  });
  Jest.test("fromIterator creates set from iterator", () => {
    let iter = Stdlib__Array_Ext.valuesIter([
      "p",
      "q",
      "r"
    ]);
    let newSet = Stdlib__Set_Ext.Value.$$String.fromIterator(iter);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$String.size(newSet)), 3);
  });
  Jest.test("values returns iterator of values", () => {
    let values = Stdlib__Set_Ext.Value.$$String.values(s).toArray();
    return Jest.Expect.toBe(Jest.Expect.expect(values.length), 3);
  });
  Jest.test("forEach iterates over values", () => {
    let values = [];
    Stdlib__Set_Ext.Value.$$String.forEach(s, v => {
      values.push(v);
    });
    return Jest.Expect.toBe(Jest.Expect.expect(values.length), 3);
  });
  Jest.test("toArray converts set to array", () => {
    let arr = Stdlib__Set_Ext.Value.$$String.toArray(s);
    return Jest.Expect.toBe(Jest.Expect.expect(arr.length), 3);
  });
  Jest.test("difference", () => {
    let s2 = Stdlib__Set_Ext.Value.$$String.make();
    Stdlib__Set_Ext.Value.$$String.add(s2, "b");
    let diff = Stdlib__Set_Ext.Value.$$String.difference(s, s2);
    return Jest.Expect.toEqual(Jest.Expect.expect([
      Stdlib__Set_Ext.Value.$$String.has(diff, "a"),
      Stdlib__Set_Ext.Value.$$String.has(diff, "b"),
      Stdlib__Set_Ext.Value.$$String.has(diff, "c")
    ]), [
      true,
      false,
      true
    ]);
  });
  Jest.test("intersection", () => {
    let s2 = Stdlib__Set_Ext.Value.$$String.make();
    Stdlib__Set_Ext.Value.$$String.add(s2, "b");
    Stdlib__Set_Ext.Value.$$String.add(s2, "d");
    let inter = Stdlib__Set_Ext.Value.$$String.intersection(s, s2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$String.values(inter).toArray()), ["b"]);
  });
  Jest.test("union", () => {
    let s2 = Stdlib__Set_Ext.Value.$$String.make();
    Stdlib__Set_Ext.Value.$$String.add(s2, "d");
    Stdlib__Set_Ext.Value.$$String.add(s2, "e");
    let union = Stdlib__Set_Ext.Value.$$String.union(s, s2);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$String.size(union)), 5);
  });
  Jest.test("symmetricDifference", () => {
    let s2 = Stdlib__Set_Ext.Value.$$String.make();
    Stdlib__Set_Ext.Value.$$String.add(s2, "b");
    Stdlib__Set_Ext.Value.$$String.add(s2, "d");
    let symDiff = Stdlib__Set_Ext.Value.$$String.symmetricDifference(s, s2);
    return Jest.Expect.toEqual(Jest.Expect.expect([
      Stdlib__Set_Ext.Value.$$String.has(symDiff, "a"),
      Stdlib__Set_Ext.Value.$$String.has(symDiff, "b"),
      Stdlib__Set_Ext.Value.$$String.has(symDiff, "c"),
      Stdlib__Set_Ext.Value.$$String.has(symDiff, "d")
    ]), [
      true,
      false,
      true,
      true
    ]);
  });
  Jest.test("isSubsetOf", () => {
    let s2 = Stdlib__Set_Ext.Value.$$String.make();
    Stdlib__Set_Ext.Value.$$String.add(s2, "a");
    Stdlib__Set_Ext.Value.$$String.add(s2, "b");
    Stdlib__Set_Ext.Value.$$String.add(s2, "c");
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$String.isSubsetOf(s, s2)), true);
  });
  Jest.test("isSupersetOf", () => {
    let s2 = Stdlib__Set_Ext.Value.$$String.make();
    Stdlib__Set_Ext.Value.$$String.add(s2, "a");
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$String.isSupersetOf(s, s2)), true);
  });
  Jest.test("isDisjointFrom", () => {
    let s2 = Stdlib__Set_Ext.Value.$$String.make();
    Stdlib__Set_Ext.Value.$$String.add(s2, "z");
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$String.isDisjointFrom(s, s2)), true);
  });
  Jest.test("ignore discards the set", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$String.ignore(s)), undefined));
});

Jest.describe("PrimFloat", () => {
  let s = Stdlib__Set_Ext.Value.Float.make();
  beforeEach(() => {
    Stdlib__Set_Ext.Value.Float.clear(s);
    Stdlib__Set_Ext.Value.Float.add(s, 1.1);
    Stdlib__Set_Ext.Value.Float.add(s, 2.2);
    Stdlib__Set_Ext.Value.Float.add(s, 3.3);
  });
  Jest.test("make creates empty set", () => {
    let newSet = Stdlib__Set_Ext.Value.Float.make();
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Float.size(newSet)), 0);
  });
  Jest.test("size returns correct count", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Float.size(s)), 3));
  Jest.test("add adds new value", () => {
    Stdlib__Set_Ext.Value.Float.add(s, 4.4);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Float.size(s)), 4);
  });
  Jest.test("add doesn't duplicate existing value", () => {
    Stdlib__Set_Ext.Value.Float.add(s, 1.1);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Float.size(s)), 3);
  });
  Jest.test("has returns true for existing value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Float.has(s, 2.2)), true));
  Jest.test("has returns false for missing value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Float.has(s, 9.9)), false));
  Jest.test("delete removes existing value", () => {
    let deleted = Stdlib__Set_Ext.Value.Float.$$delete(s, 1.1);
    return Jest.Expect.toEqual(Jest.Expect.expect([
      deleted,
      Stdlib__Set_Ext.Value.Float.has(s, 1.1)
    ]), [
      true,
      false
    ]);
  });
  Jest.test("delete returns false for missing value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Float.$$delete(s, 9.9)), false));
  Jest.test("clear removes all values", () => {
    Stdlib__Set_Ext.Value.Float.clear(s);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Float.size(s)), 0);
  });
  Jest.test("isEmpty returns false for non-empty set", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Float.isEmpty(s)), false));
  Jest.test("isEmpty returns true for empty set", () => {
    let emptySet = Stdlib__Set_Ext.Value.Float.make();
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Float.isEmpty(emptySet)), true);
  });
  Jest.test("fromArray creates set from array", () => {
    let arr = [
      5.5,
      6.6,
      7.7
    ];
    let newSet = Stdlib__Set_Ext.Value.Float.fromArray(arr);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Float.size(newSet)), 3);
  });
  Jest.test("fromIterator creates set from iterator", () => {
    let iter = Stdlib__Array_Ext.valuesIter([
      10.1,
      20.2,
      30.3
    ]);
    let newSet = Stdlib__Set_Ext.Value.Float.fromIterator(iter);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Float.size(newSet)), 3);
  });
  Jest.test("values returns iterator of values", () => {
    let values = Stdlib__Set_Ext.Value.Float.values(s).toArray();
    return Jest.Expect.toBe(Jest.Expect.expect(values.length), 3);
  });
  Jest.test("forEach iterates over values", () => {
    let values = [];
    Stdlib__Set_Ext.Value.Float.forEach(s, v => {
      values.push(v);
    });
    return Jest.Expect.toBe(Jest.Expect.expect(values.length), 3);
  });
  Jest.test("toArray converts set to array", () => {
    let arr = Stdlib__Set_Ext.Value.Float.toArray(s);
    return Jest.Expect.toBe(Jest.Expect.expect(arr.length), 3);
  });
  Jest.test("difference", () => {
    let s2 = Stdlib__Set_Ext.Value.Float.make();
    Stdlib__Set_Ext.Value.Float.add(s2, 2.2);
    let diff = Stdlib__Set_Ext.Value.Float.difference(s, s2);
    return Jest.Expect.toEqual(Jest.Expect.expect([
      Stdlib__Set_Ext.Value.Float.has(diff, 1.1),
      Stdlib__Set_Ext.Value.Float.has(diff, 2.2),
      Stdlib__Set_Ext.Value.Float.has(diff, 3.3)
    ]), [
      true,
      false,
      true
    ]);
  });
  Jest.test("intersection", () => {
    let s2 = Stdlib__Set_Ext.Value.Float.make();
    Stdlib__Set_Ext.Value.Float.add(s2, 2.2);
    Stdlib__Set_Ext.Value.Float.add(s2, 4.4);
    let inter = Stdlib__Set_Ext.Value.Float.intersection(s, s2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.Float.values(inter).toArray()), [2.2]);
  });
  Jest.test("union", () => {
    let s2 = Stdlib__Set_Ext.Value.Float.make();
    Stdlib__Set_Ext.Value.Float.add(s2, 4.4);
    Stdlib__Set_Ext.Value.Float.add(s2, 5.5);
    let union = Stdlib__Set_Ext.Value.Float.union(s, s2);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Float.size(union)), 5);
  });
  Jest.test("symmetricDifference", () => {
    let s2 = Stdlib__Set_Ext.Value.Float.make();
    Stdlib__Set_Ext.Value.Float.add(s2, 2.2);
    Stdlib__Set_Ext.Value.Float.add(s2, 4.4);
    let symDiff = Stdlib__Set_Ext.Value.Float.symmetricDifference(s, s2);
    return Jest.Expect.toEqual(Jest.Expect.expect([
      Stdlib__Set_Ext.Value.Float.has(symDiff, 1.1),
      Stdlib__Set_Ext.Value.Float.has(symDiff, 2.2),
      Stdlib__Set_Ext.Value.Float.has(symDiff, 3.3),
      Stdlib__Set_Ext.Value.Float.has(symDiff, 4.4)
    ]), [
      true,
      false,
      true,
      true
    ]);
  });
  Jest.test("isSubsetOf", () => {
    let s2 = Stdlib__Set_Ext.Value.Float.make();
    Stdlib__Set_Ext.Value.Float.add(s2, 1.1);
    Stdlib__Set_Ext.Value.Float.add(s2, 2.2);
    Stdlib__Set_Ext.Value.Float.add(s2, 3.3);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Float.isSubsetOf(s, s2)), true);
  });
  Jest.test("isSupersetOf", () => {
    let s2 = Stdlib__Set_Ext.Value.Float.make();
    Stdlib__Set_Ext.Value.Float.add(s2, 1.1);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Float.isSupersetOf(s, s2)), true);
  });
  Jest.test("isDisjointFrom", () => {
    let s2 = Stdlib__Set_Ext.Value.Float.make();
    Stdlib__Set_Ext.Value.Float.add(s2, 9.9);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Float.isDisjointFrom(s, s2)), true);
  });
  Jest.test("ignore discards the set", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Float.ignore(s)), undefined));
});

Jest.describe("PrimBigInt", () => {
  let s = Stdlib__Set_Ext.Value.$$BigInt.make();
  beforeEach(() => {
    Stdlib__Set_Ext.Value.$$BigInt.clear(s);
    Stdlib__Set_Ext.Value.$$BigInt.add(s, 1n);
    Stdlib__Set_Ext.Value.$$BigInt.add(s, 2n);
    Stdlib__Set_Ext.Value.$$BigInt.add(s, 3n);
  });
  Jest.test("make creates empty set", () => {
    let newSet = Stdlib__Set_Ext.Value.$$BigInt.make();
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$BigInt.size(newSet)), 0);
  });
  Jest.test("size returns correct count", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$BigInt.size(s)), 3));
  Jest.test("add adds new value", () => {
    Stdlib__Set_Ext.Value.$$BigInt.add(s, 4n);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$BigInt.size(s)), 4);
  });
  Jest.test("add doesn't duplicate existing value", () => {
    Stdlib__Set_Ext.Value.$$BigInt.add(s, 1n);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$BigInt.size(s)), 3);
  });
  Jest.test("has returns true for existing value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$BigInt.has(s, 2n)), true));
  Jest.test("has returns false for missing value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$BigInt.has(s, 99n)), false));
  Jest.test("delete removes existing value", () => {
    let deleted = Stdlib__Set_Ext.Value.$$BigInt.$$delete(s, 1n);
    return Jest.Expect.toEqual(Jest.Expect.expect([
      deleted,
      Stdlib__Set_Ext.Value.$$BigInt.has(s, 1n)
    ]), [
      true,
      false
    ]);
  });
  Jest.test("delete returns false for missing value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$BigInt.$$delete(s, 99n)), false));
  Jest.test("clear removes all values", () => {
    Stdlib__Set_Ext.Value.$$BigInt.clear(s);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$BigInt.size(s)), 0);
  });
  Jest.test("isEmpty returns false for non-empty set", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$BigInt.isEmpty(s)), false));
  Jest.test("isEmpty returns true for empty set", () => {
    let emptySet = Stdlib__Set_Ext.Value.$$BigInt.make();
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$BigInt.isEmpty(emptySet)), true);
  });
  Jest.test("fromArray creates set from array", () => {
    let arr = [
      5n,
      6n,
      7n
    ];
    let newSet = Stdlib__Set_Ext.Value.$$BigInt.fromArray(arr);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$BigInt.size(newSet)), 3);
  });
  Jest.test("fromIterator creates set from iterator", () => {
    let iter = Stdlib__Array_Ext.valuesIter([
      10n,
      20n,
      30n
    ]);
    let newSet = Stdlib__Set_Ext.Value.$$BigInt.fromIterator(iter);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$BigInt.size(newSet)), 3);
  });
  Jest.test("values returns iterator of values", () => {
    let values = Stdlib__Set_Ext.Value.$$BigInt.values(s).toArray();
    return Jest.Expect.toBe(Jest.Expect.expect(values.length), 3);
  });
  Jest.test("forEach iterates over values", () => {
    let values = [];
    Stdlib__Set_Ext.Value.$$BigInt.forEach(s, v => {
      values.push(v);
    });
    return Jest.Expect.toBe(Jest.Expect.expect(values.length), 3);
  });
  Jest.test("toArray converts set to array", () => {
    let arr = Stdlib__Set_Ext.Value.$$BigInt.toArray(s);
    return Jest.Expect.toBe(Jest.Expect.expect(arr.length), 3);
  });
  Jest.test("difference", () => {
    let s2 = Stdlib__Set_Ext.Value.$$BigInt.make();
    Stdlib__Set_Ext.Value.$$BigInt.add(s2, 2n);
    let diff = Stdlib__Set_Ext.Value.$$BigInt.difference(s, s2);
    return Jest.Expect.toEqual(Jest.Expect.expect([
      Stdlib__Set_Ext.Value.$$BigInt.has(diff, 1n),
      Stdlib__Set_Ext.Value.$$BigInt.has(diff, 2n),
      Stdlib__Set_Ext.Value.$$BigInt.has(diff, 3n)
    ]), [
      true,
      false,
      true
    ]);
  });
  Jest.test("intersection", () => {
    let s2 = Stdlib__Set_Ext.Value.$$BigInt.make();
    Stdlib__Set_Ext.Value.$$BigInt.add(s2, 2n);
    Stdlib__Set_Ext.Value.$$BigInt.add(s2, 4n);
    let inter = Stdlib__Set_Ext.Value.$$BigInt.intersection(s, s2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$BigInt.values(inter).toArray()), [2n]);
  });
  Jest.test("union", () => {
    let s2 = Stdlib__Set_Ext.Value.$$BigInt.make();
    Stdlib__Set_Ext.Value.$$BigInt.add(s2, 4n);
    Stdlib__Set_Ext.Value.$$BigInt.add(s2, 5n);
    let union = Stdlib__Set_Ext.Value.$$BigInt.union(s, s2);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$BigInt.size(union)), 5);
  });
  Jest.test("symmetricDifference", () => {
    let s2 = Stdlib__Set_Ext.Value.$$BigInt.make();
    Stdlib__Set_Ext.Value.$$BigInt.add(s2, 2n);
    Stdlib__Set_Ext.Value.$$BigInt.add(s2, 4n);
    let symDiff = Stdlib__Set_Ext.Value.$$BigInt.symmetricDifference(s, s2);
    return Jest.Expect.toEqual(Jest.Expect.expect([
      Stdlib__Set_Ext.Value.$$BigInt.has(symDiff, 1n),
      Stdlib__Set_Ext.Value.$$BigInt.has(symDiff, 2n),
      Stdlib__Set_Ext.Value.$$BigInt.has(symDiff, 3n),
      Stdlib__Set_Ext.Value.$$BigInt.has(symDiff, 4n)
    ]), [
      true,
      false,
      true,
      true
    ]);
  });
  Jest.test("isSubsetOf", () => {
    let s2 = Stdlib__Set_Ext.Value.$$BigInt.make();
    Stdlib__Set_Ext.Value.$$BigInt.add(s2, 1n);
    Stdlib__Set_Ext.Value.$$BigInt.add(s2, 2n);
    Stdlib__Set_Ext.Value.$$BigInt.add(s2, 3n);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$BigInt.isSubsetOf(s, s2)), true);
  });
  Jest.test("isSupersetOf", () => {
    let s2 = Stdlib__Set_Ext.Value.$$BigInt.make();
    Stdlib__Set_Ext.Value.$$BigInt.add(s2, 1n);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$BigInt.isSupersetOf(s, s2)), true);
  });
  Jest.test("isDisjointFrom", () => {
    let s2 = Stdlib__Set_Ext.Value.$$BigInt.make();
    Stdlib__Set_Ext.Value.$$BigInt.add(s2, 10n);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$BigInt.isDisjointFrom(s, s2)), true);
  });
  Jest.test("ignore discards the set", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$BigInt.ignore(s)), undefined));
});

Jest.describe("PrimSymbol", () => {
  let sym1 = Symbol("symbol1");
  let sym2 = Symbol("symbol2");
  let sym3 = Symbol("symbol3");
  let s = Stdlib__Set_Ext.Value.$$Symbol.make();
  beforeEach(() => {
    Stdlib__Set_Ext.Value.$$Symbol.clear(s);
    Stdlib__Set_Ext.Value.$$Symbol.add(s, sym1);
    Stdlib__Set_Ext.Value.$$Symbol.add(s, sym2);
    Stdlib__Set_Ext.Value.$$Symbol.add(s, sym3);
  });
  Jest.test("make creates empty set", () => {
    let newSet = Stdlib__Set_Ext.Value.$$Symbol.make();
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Symbol.size(newSet)), 0);
  });
  Jest.test("size returns correct count", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Symbol.size(s)), 3));
  Jest.test("add adds new value", () => {
    let sym4 = Symbol("symbol4");
    Stdlib__Set_Ext.Value.$$Symbol.add(s, sym4);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Symbol.size(s)), 4);
  });
  Jest.test("add doesn't duplicate existing value", () => {
    Stdlib__Set_Ext.Value.$$Symbol.add(s, sym1);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Symbol.size(s)), 3);
  });
  Jest.test("has returns true for existing value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Symbol.has(s, sym2)), true));
  Jest.test("has returns false for missing value", () => {
    let otherSym = Symbol("other");
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Symbol.has(s, otherSym)), false);
  });
  Jest.test("delete removes existing value", () => {
    let deleted = Stdlib__Set_Ext.Value.$$Symbol.$$delete(s, sym1);
    return Jest.Expect.toEqual(Jest.Expect.expect([
      deleted,
      Stdlib__Set_Ext.Value.$$Symbol.has(s, sym1)
    ]), [
      true,
      false
    ]);
  });
  Jest.test("delete returns false for missing value", () => {
    let otherSym = Symbol("other");
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Symbol.$$delete(s, otherSym)), false);
  });
  Jest.test("clear removes all values", () => {
    Stdlib__Set_Ext.Value.$$Symbol.clear(s);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Symbol.size(s)), 0);
  });
  Jest.test("isEmpty returns false for non-empty set", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Symbol.isEmpty(s)), false));
  Jest.test("isEmpty returns true for empty set", () => {
    let emptySet = Stdlib__Set_Ext.Value.$$Symbol.make();
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Symbol.isEmpty(emptySet)), true);
  });
  Jest.test("fromArray creates set from array", () => {
    let s1 = Symbol("a");
    let s2 = Symbol("b");
    let s3 = Symbol("c");
    let arr = [
      s1,
      s2,
      s3
    ];
    let newSet = Stdlib__Set_Ext.Value.$$Symbol.fromArray(arr);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Symbol.size(newSet)), 3);
  });
  Jest.test("fromIterator creates set from iterator", () => {
    let s1 = Symbol("x");
    let s2 = Symbol("y");
    let s3 = Symbol("z");
    let iter = Stdlib__Array_Ext.valuesIter([
      s1,
      s2,
      s3
    ]);
    let newSet = Stdlib__Set_Ext.Value.$$Symbol.fromIterator(iter);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Symbol.size(newSet)), 3);
  });
  Jest.test("values returns iterator of values", () => {
    let values = Stdlib__Set_Ext.Value.$$Symbol.values(s).toArray();
    return Jest.Expect.toBe(Jest.Expect.expect(values.length), 3);
  });
  Jest.test("forEach iterates over values", () => {
    let values = [];
    Stdlib__Set_Ext.Value.$$Symbol.forEach(s, v => {
      values.push(v);
    });
    return Jest.Expect.toBe(Jest.Expect.expect(values.length), 3);
  });
  Jest.test("toArray converts set to array", () => {
    let arr = Stdlib__Set_Ext.Value.$$Symbol.toArray(s);
    return Jest.Expect.toBe(Jest.Expect.expect(arr.length), 3);
  });
  Jest.test("difference", () => {
    let s2 = Stdlib__Set_Ext.Value.$$Symbol.make();
    Stdlib__Set_Ext.Value.$$Symbol.add(s2, sym2);
    let diff = Stdlib__Set_Ext.Value.$$Symbol.difference(s, s2);
    return Jest.Expect.toEqual(Jest.Expect.expect([
      Stdlib__Set_Ext.Value.$$Symbol.has(diff, sym1),
      Stdlib__Set_Ext.Value.$$Symbol.has(diff, sym2),
      Stdlib__Set_Ext.Value.$$Symbol.has(diff, sym3)
    ]), [
      true,
      false,
      true
    ]);
  });
  Jest.test("intersection", () => {
    let sym4 = Symbol("symbol4");
    let s2 = Stdlib__Set_Ext.Value.$$Symbol.make();
    Stdlib__Set_Ext.Value.$$Symbol.add(s2, sym2);
    Stdlib__Set_Ext.Value.$$Symbol.add(s2, sym4);
    let inter = Stdlib__Set_Ext.Value.$$Symbol.intersection(s, s2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Symbol.values(inter).toArray()), [sym2]);
  });
  Jest.test("union", () => {
    let sym4 = Symbol("symbol4");
    let sym5 = Symbol("symbol5");
    let s2 = Stdlib__Set_Ext.Value.$$Symbol.make();
    Stdlib__Set_Ext.Value.$$Symbol.add(s2, sym4);
    Stdlib__Set_Ext.Value.$$Symbol.add(s2, sym5);
    let union = Stdlib__Set_Ext.Value.$$Symbol.union(s, s2);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Symbol.size(union)), 5);
  });
  Jest.test("symmetricDifference", () => {
    let sym4 = Symbol("symbol4");
    let s2 = Stdlib__Set_Ext.Value.$$Symbol.make();
    Stdlib__Set_Ext.Value.$$Symbol.add(s2, sym2);
    Stdlib__Set_Ext.Value.$$Symbol.add(s2, sym4);
    let symDiff = Stdlib__Set_Ext.Value.$$Symbol.symmetricDifference(s, s2);
    return Jest.Expect.toEqual(Jest.Expect.expect([
      Stdlib__Set_Ext.Value.$$Symbol.has(symDiff, sym1),
      Stdlib__Set_Ext.Value.$$Symbol.has(symDiff, sym2),
      Stdlib__Set_Ext.Value.$$Symbol.has(symDiff, sym3),
      Stdlib__Set_Ext.Value.$$Symbol.has(symDiff, sym4)
    ]), [
      true,
      false,
      true,
      true
    ]);
  });
  Jest.test("isSubsetOf", () => {
    let s2 = Stdlib__Set_Ext.Value.$$Symbol.make();
    Stdlib__Set_Ext.Value.$$Symbol.add(s2, sym1);
    Stdlib__Set_Ext.Value.$$Symbol.add(s2, sym2);
    Stdlib__Set_Ext.Value.$$Symbol.add(s2, sym3);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Symbol.isSubsetOf(s, s2)), true);
  });
  Jest.test("isSupersetOf", () => {
    let s2 = Stdlib__Set_Ext.Value.$$Symbol.make();
    Stdlib__Set_Ext.Value.$$Symbol.add(s2, sym1);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Symbol.isSupersetOf(s, s2)), true);
  });
  Jest.test("isDisjointFrom", () => {
    let otherSym = Symbol("other");
    let s2 = Stdlib__Set_Ext.Value.$$Symbol.make();
    Stdlib__Set_Ext.Value.$$Symbol.add(s2, otherSym);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Symbol.isDisjointFrom(s, s2)), true);
  });
  Jest.test("ignore discards the set", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Symbol.ignore(s)), undefined));
});

Jest.describe("ArrayInt", () => {
  let si = Stdlib__Set_Ext.Value.$$Array.Int.make();
  beforeEach(() => {
    Stdlib__Set_Ext.Value.$$Array.Int.clear(si);
    Stdlib__Set_Ext.Value.$$Array.Int.add(si, [
      1,
      2,
      3
    ]);
    Stdlib__Set_Ext.Value.$$Array.Int.add(si, [
      4,
      5,
      6
    ]);
    Stdlib__Set_Ext.Value.$$Array.Int.add(si, [
      7,
      8,
      9
    ]);
  });
  Jest.test("clear all values", () => {
    Stdlib__Set_Ext.Value.$$Array.Int.clear(si);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Int.size(si)), 0);
  });
  Jest.test("forEach", () => {
    let values = [];
    Stdlib__Set_Ext.Value.$$Array.Int.forEach(si, v => {
      values.push(v);
    });
    return Jest.Expect.toEqual(Jest.Expect.expect(values), [
      [
        1,
        2,
        3
      ],
      [
        4,
        5,
        6
      ],
      [
        7,
        8,
        9
      ]
    ]);
  });
  Jest.test("has value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Int.has(si, [
    1,
    2,
    3
  ])), true));
  Jest.test("delete value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Int.$$delete(si, [
    1,
    2,
    3
  ])), true));
  Jest.test("fromArray", () => {
    let arr = [
      [
        1,
        2,
        3
      ],
      [
        4,
        5,
        6
      ]
    ];
    let si = Stdlib__Set_Ext.Value.$$Array.Int.fromArray(arr);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Int.size(si)), 2);
  });
  Jest.test("fromIterator", () => {
    let iter = Stdlib__Array_Ext.valuesIter([
      [
        1,
        2,
        3
      ],
      [
        4,
        5,
        6
      ]
    ]);
    let si = Stdlib__Set_Ext.Value.$$Array.Int.fromIterator(iter);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Int.size(si)), 2);
  });
  Jest.test("values", () => {
    let values = Stdlib__Set_Ext.Value.$$Array.Int.values(si).toArray();
    return Jest.Expect.toEqual(Jest.Expect.expect(values), [
      [
        1,
        2,
        3
      ],
      [
        4,
        5,
        6
      ],
      [
        7,
        8,
        9
      ]
    ]);
  });
  Jest.test("difference", () => {
    let si2 = Stdlib__Set_Ext.Value.$$Array.Int.make();
    Stdlib__Set_Ext.Value.$$Array.Int.add(si2, [
      4,
      5,
      6
    ]);
    let diff = Stdlib__Set_Ext.Value.$$Array.Int.difference(si, si2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Int.values(diff).toArray()), [
      [
        1,
        2,
        3
      ],
      [
        7,
        8,
        9
      ]
    ]);
  });
  Jest.test("intersection", () => {
    let si2 = Stdlib__Set_Ext.Value.$$Array.Int.make();
    Stdlib__Set_Ext.Value.$$Array.Int.add(si2, [
      4,
      5,
      6
    ]);
    let inter = Stdlib__Set_Ext.Value.$$Array.Int.intersection(si, si2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Int.values(inter).toArray()), [[
        4,
        5,
        6
      ]]);
  });
  Jest.test("union", () => {
    let si2 = Stdlib__Set_Ext.Value.$$Array.Int.make();
    Stdlib__Set_Ext.Value.$$Array.Int.add(si2, [
      10,
      11,
      12
    ]);
    let union = Stdlib__Set_Ext.Value.$$Array.Int.union(si, si2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Int.values(union).toArray()), [
      [
        1,
        2,
        3
      ],
      [
        4,
        5,
        6
      ],
      [
        7,
        8,
        9
      ],
      [
        10,
        11,
        12
      ]
    ]);
  });
  Jest.test("symmetricDifference", () => {
    let si2 = Stdlib__Set_Ext.Value.$$Array.Int.make();
    Stdlib__Set_Ext.Value.$$Array.Int.add(si2, [
      4,
      5,
      6
    ]);
    Stdlib__Set_Ext.Value.$$Array.Int.add(si2, [
      10,
      11,
      12
    ]);
    let symDiff = Stdlib__Set_Ext.Value.$$Array.Int.symmetricDifference(si, si2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Int.values(symDiff).toArray()), [
      [
        1,
        2,
        3
      ],
      [
        7,
        8,
        9
      ],
      [
        10,
        11,
        12
      ]
    ]);
  });
  Jest.test("isSubsetOf", () => {
    let si2 = Stdlib__Set_Ext.Value.$$Array.Int.make();
    Stdlib__Set_Ext.Value.$$Array.Int.add(si2, [
      1,
      2,
      3
    ]);
    Stdlib__Set_Ext.Value.$$Array.Int.add(si2, [
      4,
      5,
      6
    ]);
    Stdlib__Set_Ext.Value.$$Array.Int.add(si2, [
      7,
      8,
      9
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Int.isSubsetOf(si, si2)), true);
  });
  Jest.test("isSupersetOf", () => {
    let si2 = Stdlib__Set_Ext.Value.$$Array.Int.make();
    Stdlib__Set_Ext.Value.$$Array.Int.add(si2, [
      1,
      2,
      3
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Int.isSupersetOf(si, si2)), true);
  });
  Jest.test("isDisjointFrom", () => {
    let si2 = Stdlib__Set_Ext.Value.$$Array.Int.make();
    Stdlib__Set_Ext.Value.$$Array.Int.add(si2, [
      10,
      11,
      12
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Int.isDisjointFrom(si, si2)), true);
  });
  Jest.test("isEmpty returns false for non-empty set", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Int.isEmpty(si)), false));
  Jest.test("isEmpty returns true for empty set", () => {
    let si2 = Stdlib__Set_Ext.Value.$$Array.Int.make();
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Int.isEmpty(si2)), true);
  });
  Jest.test("toArray converts set to array", () => {
    let arr = Stdlib__Set_Ext.Value.$$Array.Int.toArray(si);
    return Jest.Expect.toEqual(Jest.Expect.expect(arr), [
      [
        1,
        2,
        3
      ],
      [
        4,
        5,
        6
      ],
      [
        7,
        8,
        9
      ]
    ]);
  });
  Jest.test("ignore discards the set", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Int.ignore(si)), undefined));
});

Jest.describe("ArrayString", () => {
  let ss = Stdlib__Set_Ext.Value.$$Array.$$String.make();
  beforeEach(() => {
    Stdlib__Set_Ext.Value.$$Array.$$String.clear(ss);
    Stdlib__Set_Ext.Value.$$Array.$$String.add(ss, [
      "a",
      "b",
      "c"
    ]);
    Stdlib__Set_Ext.Value.$$Array.$$String.add(ss, [
      "d",
      "e",
      "f"
    ]);
    Stdlib__Set_Ext.Value.$$Array.$$String.add(ss, [
      "g",
      "h",
      "i"
    ]);
  });
  Jest.test("clear all values", () => {
    Stdlib__Set_Ext.Value.$$Array.$$String.clear(ss);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.$$String.size(ss)), 0);
  });
  Jest.test("forEach", () => {
    let values = [];
    Stdlib__Set_Ext.Value.$$Array.$$String.forEach(ss, v => {
      values.push(v);
    });
    return Jest.Expect.toEqual(Jest.Expect.expect(values), [
      [
        "a",
        "b",
        "c"
      ],
      [
        "d",
        "e",
        "f"
      ],
      [
        "g",
        "h",
        "i"
      ]
    ]);
  });
  Jest.test("has value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.$$String.has(ss, [
    "a",
    "b",
    "c"
  ])), true));
  Jest.test("delete value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.$$String.$$delete(ss, [
    "a",
    "b",
    "c"
  ])), true));
  Jest.test("fromArray", () => {
    let arr = [
      [
        "a",
        "b",
        "c"
      ],
      [
        "d",
        "e",
        "f"
      ]
    ];
    let ss = Stdlib__Set_Ext.Value.$$Array.$$String.fromArray(arr);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.$$String.size(ss)), 2);
  });
  Jest.test("fromIterator", () => {
    let iter = Stdlib__Array_Ext.valuesIter([
      [
        "a",
        "b",
        "c"
      ],
      [
        "d",
        "e",
        "f"
      ]
    ]);
    let ss = Stdlib__Set_Ext.Value.$$Array.$$String.fromIterator(iter);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.$$String.size(ss)), 2);
  });
  Jest.test("values", () => {
    let values = Stdlib__Set_Ext.Value.$$Array.$$String.values(ss).toArray();
    return Jest.Expect.toEqual(Jest.Expect.expect(values), [
      [
        "a",
        "b",
        "c"
      ],
      [
        "d",
        "e",
        "f"
      ],
      [
        "g",
        "h",
        "i"
      ]
    ]);
  });
  Jest.test("difference", () => {
    let ss2 = Stdlib__Set_Ext.Value.$$Array.$$String.make();
    Stdlib__Set_Ext.Value.$$Array.$$String.add(ss2, [
      "d",
      "e",
      "f"
    ]);
    let diff = Stdlib__Set_Ext.Value.$$Array.$$String.difference(ss, ss2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.$$String.values(diff).toArray()), [
      [
        "a",
        "b",
        "c"
      ],
      [
        "g",
        "h",
        "i"
      ]
    ]);
  });
  Jest.test("intersection", () => {
    let ss2 = Stdlib__Set_Ext.Value.$$Array.$$String.make();
    Stdlib__Set_Ext.Value.$$Array.$$String.add(ss2, [
      "d",
      "e",
      "f"
    ]);
    let inter = Stdlib__Set_Ext.Value.$$Array.$$String.intersection(ss, ss2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.$$String.values(inter).toArray()), [[
        "d",
        "e",
        "f"
      ]]);
  });
  Jest.test("union", () => {
    let ss2 = Stdlib__Set_Ext.Value.$$Array.$$String.make();
    Stdlib__Set_Ext.Value.$$Array.$$String.add(ss2, [
      "j",
      "k",
      "l"
    ]);
    let union = Stdlib__Set_Ext.Value.$$Array.$$String.union(ss, ss2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.$$String.values(union).toArray()), [
      [
        "a",
        "b",
        "c"
      ],
      [
        "d",
        "e",
        "f"
      ],
      [
        "g",
        "h",
        "i"
      ],
      [
        "j",
        "k",
        "l"
      ]
    ]);
  });
  Jest.test("symmetricDifference", () => {
    let ss2 = Stdlib__Set_Ext.Value.$$Array.$$String.make();
    Stdlib__Set_Ext.Value.$$Array.$$String.add(ss2, [
      "d",
      "e",
      "f"
    ]);
    Stdlib__Set_Ext.Value.$$Array.$$String.add(ss2, [
      "j",
      "k",
      "l"
    ]);
    let symDiff = Stdlib__Set_Ext.Value.$$Array.$$String.symmetricDifference(ss, ss2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.$$String.values(symDiff).toArray()), [
      [
        "a",
        "b",
        "c"
      ],
      [
        "g",
        "h",
        "i"
      ],
      [
        "j",
        "k",
        "l"
      ]
    ]);
  });
  Jest.test("isSubsetOf", () => {
    let ss2 = Stdlib__Set_Ext.Value.$$Array.$$String.make();
    Stdlib__Set_Ext.Value.$$Array.$$String.add(ss2, [
      "a",
      "b",
      "c"
    ]);
    Stdlib__Set_Ext.Value.$$Array.$$String.add(ss2, [
      "d",
      "e",
      "f"
    ]);
    Stdlib__Set_Ext.Value.$$Array.$$String.add(ss2, [
      "g",
      "h",
      "i"
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.$$String.isSubsetOf(ss, ss2)), true);
  });
  Jest.test("isSupersetOf", () => {
    let ss2 = Stdlib__Set_Ext.Value.$$Array.$$String.make();
    Stdlib__Set_Ext.Value.$$Array.$$String.add(ss2, [
      "a",
      "b",
      "c"
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.$$String.isSupersetOf(ss, ss2)), true);
  });
  Jest.test("isDisjointFrom", () => {
    let ss2 = Stdlib__Set_Ext.Value.$$Array.$$String.make();
    Stdlib__Set_Ext.Value.$$Array.$$String.add(ss2, [
      "j",
      "k",
      "l"
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.$$String.isDisjointFrom(ss, ss2)), true);
  });
  Jest.test("isEmpty returns false for non-empty set", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.$$String.isEmpty(ss)), false));
  Jest.test("isEmpty returns true for empty set", () => {
    let ss2 = Stdlib__Set_Ext.Value.$$Array.$$String.make();
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.$$String.isEmpty(ss2)), true);
  });
  Jest.test("toArray converts set to array", () => {
    let arr = Stdlib__Set_Ext.Value.$$Array.$$String.toArray(ss);
    return Jest.Expect.toEqual(Jest.Expect.expect(arr), [
      [
        "a",
        "b",
        "c"
      ],
      [
        "d",
        "e",
        "f"
      ],
      [
        "g",
        "h",
        "i"
      ]
    ]);
  });
  Jest.test("ignore discards the set", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.$$String.ignore(ss)), undefined));
});

Jest.describe("ArrayFloat", () => {
  let sf = Stdlib__Set_Ext.Value.$$Array.Float.make();
  beforeEach(() => {
    Stdlib__Set_Ext.Value.$$Array.Float.clear(sf);
    Stdlib__Set_Ext.Value.$$Array.Float.add(sf, [
      1.1,
      2.2,
      3.3
    ]);
    Stdlib__Set_Ext.Value.$$Array.Float.add(sf, [
      4.4,
      5.5,
      6.6
    ]);
    Stdlib__Set_Ext.Value.$$Array.Float.add(sf, [
      7.7,
      8.8,
      9.9
    ]);
  });
  Jest.test("clear all values", () => {
    Stdlib__Set_Ext.Value.$$Array.Float.clear(sf);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Float.size(sf)), 0);
  });
  Jest.test("forEach", () => {
    let values = [];
    Stdlib__Set_Ext.Value.$$Array.Float.forEach(sf, v => {
      values.push(v);
    });
    return Jest.Expect.toEqual(Jest.Expect.expect(values), [
      [
        1.1,
        2.2,
        3.3
      ],
      [
        4.4,
        5.5,
        6.6
      ],
      [
        7.7,
        8.8,
        9.9
      ]
    ]);
  });
  Jest.test("has value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Float.has(sf, [
    1.1,
    2.2,
    3.3
  ])), true));
  Jest.test("delete value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Float.$$delete(sf, [
    1.1,
    2.2,
    3.3
  ])), true));
  Jest.test("fromArray", () => {
    let arr = [
      [
        1.1,
        2.2,
        3.3
      ],
      [
        4.4,
        5.5,
        6.6
      ]
    ];
    let sf = Stdlib__Set_Ext.Value.$$Array.Float.fromArray(arr);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Float.size(sf)), 2);
  });
  Jest.test("fromIterator", () => {
    let iter = Stdlib__Array_Ext.valuesIter([
      [
        1.1,
        2.2,
        3.3
      ],
      [
        4.4,
        5.5,
        6.6
      ]
    ]);
    let sf = Stdlib__Set_Ext.Value.$$Array.Float.fromIterator(iter);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Float.size(sf)), 2);
  });
  Jest.test("values", () => {
    let values = Stdlib__Set_Ext.Value.$$Array.Float.values(sf).toArray();
    return Jest.Expect.toEqual(Jest.Expect.expect(values), [
      [
        1.1,
        2.2,
        3.3
      ],
      [
        4.4,
        5.5,
        6.6
      ],
      [
        7.7,
        8.8,
        9.9
      ]
    ]);
  });
  Jest.test("difference", () => {
    let sf2 = Stdlib__Set_Ext.Value.$$Array.Float.make();
    Stdlib__Set_Ext.Value.$$Array.Float.add(sf2, [
      4.4,
      5.5,
      6.6
    ]);
    let diff = Stdlib__Set_Ext.Value.$$Array.Float.difference(sf, sf2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Float.values(diff).toArray()), [
      [
        1.1,
        2.2,
        3.3
      ],
      [
        7.7,
        8.8,
        9.9
      ]
    ]);
  });
  Jest.test("intersection", () => {
    let sf2 = Stdlib__Set_Ext.Value.$$Array.Float.make();
    Stdlib__Set_Ext.Value.$$Array.Float.add(sf2, [
      4.4,
      5.5,
      6.6
    ]);
    let inter = Stdlib__Set_Ext.Value.$$Array.Float.intersection(sf, sf2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Float.values(inter).toArray()), [[
        4.4,
        5.5,
        6.6
      ]]);
  });
  Jest.test("union", () => {
    let sf2 = Stdlib__Set_Ext.Value.$$Array.Float.make();
    Stdlib__Set_Ext.Value.$$Array.Float.add(sf2, [
      10.1,
      11.2,
      12.3
    ]);
    let union = Stdlib__Set_Ext.Value.$$Array.Float.union(sf, sf2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Float.values(union).toArray()), [
      [
        1.1,
        2.2,
        3.3
      ],
      [
        4.4,
        5.5,
        6.6
      ],
      [
        7.7,
        8.8,
        9.9
      ],
      [
        10.1,
        11.2,
        12.3
      ]
    ]);
  });
  Jest.test("symmetricDifference", () => {
    let sf2 = Stdlib__Set_Ext.Value.$$Array.Float.make();
    Stdlib__Set_Ext.Value.$$Array.Float.add(sf2, [
      4.4,
      5.5,
      6.6
    ]);
    Stdlib__Set_Ext.Value.$$Array.Float.add(sf2, [
      10.1,
      11.2,
      12.3
    ]);
    let symDiff = Stdlib__Set_Ext.Value.$$Array.Float.symmetricDifference(sf, sf2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Float.values(symDiff).toArray()), [
      [
        1.1,
        2.2,
        3.3
      ],
      [
        7.7,
        8.8,
        9.9
      ],
      [
        10.1,
        11.2,
        12.3
      ]
    ]);
  });
  Jest.test("isSubsetOf", () => {
    let sf2 = Stdlib__Set_Ext.Value.$$Array.Float.make();
    Stdlib__Set_Ext.Value.$$Array.Float.add(sf2, [
      1.1,
      2.2,
      3.3
    ]);
    Stdlib__Set_Ext.Value.$$Array.Float.add(sf2, [
      4.4,
      5.5,
      6.6
    ]);
    Stdlib__Set_Ext.Value.$$Array.Float.add(sf2, [
      7.7,
      8.8,
      9.9
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Float.isSubsetOf(sf, sf2)), true);
  });
  Jest.test("isSupersetOf", () => {
    let sf2 = Stdlib__Set_Ext.Value.$$Array.Float.make();
    Stdlib__Set_Ext.Value.$$Array.Float.add(sf2, [
      1.1,
      2.2,
      3.3
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Float.isSupersetOf(sf, sf2)), true);
  });
  Jest.test("isDisjointFrom", () => {
    let sf2 = Stdlib__Set_Ext.Value.$$Array.Float.make();
    Stdlib__Set_Ext.Value.$$Array.Float.add(sf2, [
      10.1,
      11.2,
      12.3
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Float.isDisjointFrom(sf, sf2)), true);
  });
  Jest.test("isEmpty returns false for non-empty set", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Float.isEmpty(sf)), false));
  Jest.test("isEmpty returns true for empty set", () => {
    let sf2 = Stdlib__Set_Ext.Value.$$Array.Float.make();
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Float.isEmpty(sf2)), true);
  });
  Jest.test("toArray converts set to array", () => {
    let arr = Stdlib__Set_Ext.Value.$$Array.Float.toArray(sf);
    return Jest.Expect.toEqual(Jest.Expect.expect(arr), [
      [
        1.1,
        2.2,
        3.3
      ],
      [
        4.4,
        5.5,
        6.6
      ],
      [
        7.7,
        8.8,
        9.9
      ]
    ]);
  });
  Jest.test("ignore discards the set", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.$$Array.Float.ignore(sf)), undefined));
});

Jest.describe("SetTuple2IntString", () => {
  let stis = Stdlib__Set_Ext.Value.Tuple2.IntString.make();
  beforeEach(() => {
    Stdlib__Set_Ext.Value.Tuple2.IntString.clear(stis);
    Stdlib__Set_Ext.Value.Tuple2.IntString.add(stis, [
      1,
      "one"
    ]);
    Stdlib__Set_Ext.Value.Tuple2.IntString.add(stis, [
      2,
      "two"
    ]);
  });
  Jest.test("clear all values", () => {
    Stdlib__Set_Ext.Value.Tuple2.IntString.clear(stis);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.IntString.size(stis)), 0);
  });
  Jest.test("forEach", () => {
    let values = [];
    Stdlib__Set_Ext.Value.Tuple2.IntString.forEach(stis, v => {
      values.push(v);
    });
    return Jest.Expect.toEqual(Jest.Expect.expect(values), [
      [
        1,
        "one"
      ],
      [
        2,
        "two"
      ]
    ]);
  });
  Jest.test("has value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.IntString.has(stis, [
    1,
    "one"
  ])), true));
  Jest.test("delete value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.IntString.$$delete(stis, [
    1,
    "one"
  ])), true));
  Jest.test("fromArray", () => {
    let arr = [
      [
        1,
        "one"
      ],
      [
        2,
        "two"
      ]
    ];
    let stis = Stdlib__Set_Ext.Value.Tuple2.IntString.fromArray(arr);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.IntString.size(stis)), 2);
  });
  Jest.test("fromIterator", () => {
    let iter = Stdlib__Array_Ext.valuesIter([
      [
        1,
        "one"
      ],
      [
        2,
        "two"
      ]
    ]);
    let stis = Stdlib__Set_Ext.Value.Tuple2.IntString.fromIterator(iter);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.IntString.size(stis)), 2);
  });
  Jest.test("values", () => {
    let values = Stdlib__Set_Ext.Value.Tuple2.IntString.values(stis).toArray();
    return Jest.Expect.toEqual(Jest.Expect.expect(values), [
      [
        1,
        "one"
      ],
      [
        2,
        "two"
      ]
    ]);
  });
  Jest.test("difference", () => {
    let stis2 = Stdlib__Set_Ext.Value.Tuple2.IntString.make();
    Stdlib__Set_Ext.Value.Tuple2.IntString.add(stis2, [
      2,
      "two"
    ]);
    let diff = Stdlib__Set_Ext.Value.Tuple2.IntString.difference(stis, stis2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.IntString.values(diff).toArray()), [[
        1,
        "one"
      ]]);
  });
  Jest.test("intersection", () => {
    let stis2 = Stdlib__Set_Ext.Value.Tuple2.IntString.make();
    Stdlib__Set_Ext.Value.Tuple2.IntString.add(stis2, [
      2,
      "two"
    ]);
    let inter = Stdlib__Set_Ext.Value.Tuple2.IntString.intersection(stis, stis2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.IntString.values(inter).toArray()), [[
        2,
        "two"
      ]]);
  });
  Jest.test("union", () => {
    let stis2 = Stdlib__Set_Ext.Value.Tuple2.IntString.make();
    Stdlib__Set_Ext.Value.Tuple2.IntString.add(stis2, [
      3,
      "three"
    ]);
    let union = Stdlib__Set_Ext.Value.Tuple2.IntString.union(stis, stis2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.IntString.values(union).toArray()), [
      [
        1,
        "one"
      ],
      [
        2,
        "two"
      ],
      [
        3,
        "three"
      ]
    ]);
  });
  Jest.test("symmetricDifference", () => {
    let stis2 = Stdlib__Set_Ext.Value.Tuple2.IntString.make();
    Stdlib__Set_Ext.Value.Tuple2.IntString.add(stis2, [
      2,
      "two"
    ]);
    Stdlib__Set_Ext.Value.Tuple2.IntString.add(stis2, [
      3,
      "three"
    ]);
    let symDiff = Stdlib__Set_Ext.Value.Tuple2.IntString.symmetricDifference(stis, stis2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.IntString.values(symDiff).toArray()), [
      [
        1,
        "one"
      ],
      [
        3,
        "three"
      ]
    ]);
  });
  Jest.test("isSubsetOf", () => {
    let stis2 = Stdlib__Set_Ext.Value.Tuple2.IntString.make();
    Stdlib__Set_Ext.Value.Tuple2.IntString.add(stis2, [
      1,
      "one"
    ]);
    Stdlib__Set_Ext.Value.Tuple2.IntString.add(stis2, [
      2,
      "two"
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.IntString.isSubsetOf(stis, stis2)), true);
  });
  Jest.test("isSupersetOf", () => {
    let stis2 = Stdlib__Set_Ext.Value.Tuple2.IntString.make();
    Stdlib__Set_Ext.Value.Tuple2.IntString.add(stis2, [
      1,
      "one"
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.IntString.isSupersetOf(stis, stis2)), true);
  });
  Jest.test("isDisjointFrom", () => {
    let stis2 = Stdlib__Set_Ext.Value.Tuple2.IntString.make();
    Stdlib__Set_Ext.Value.Tuple2.IntString.add(stis2, [
      3,
      "three"
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.IntString.isDisjointFrom(stis, stis2)), true);
  });
  Jest.test("isEmpty returns false for non-empty set", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.IntString.isEmpty(stis)), false));
  Jest.test("isEmpty returns true for empty set", () => {
    let stis2 = Stdlib__Set_Ext.Value.Tuple2.IntString.make();
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.IntString.isEmpty(stis2)), true);
  });
  Jest.test("toArray converts set to array", () => {
    let arr = Stdlib__Set_Ext.Value.Tuple2.IntString.toArray(stis);
    return Jest.Expect.toEqual(Jest.Expect.expect(arr), [
      [
        1,
        "one"
      ],
      [
        2,
        "two"
      ]
    ]);
  });
  Jest.test("ignore discards the set", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.IntString.ignore(stis)), undefined));
});

Jest.describe("SetTuple2FloatFloat", () => {
  let stff = Stdlib__Set_Ext.Value.Tuple2.FloatFloat.make();
  beforeEach(() => {
    Stdlib__Set_Ext.Value.Tuple2.FloatFloat.clear(stff);
    Stdlib__Set_Ext.Value.Tuple2.FloatFloat.add(stff, [
      1.1,
      2.2
    ]);
    Stdlib__Set_Ext.Value.Tuple2.FloatFloat.add(stff, [
      3.3,
      4.4
    ]);
  });
  Jest.test("clear all values", () => {
    Stdlib__Set_Ext.Value.Tuple2.FloatFloat.clear(stff);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.FloatFloat.size(stff)), 0);
  });
  Jest.test("forEach", () => {
    let values = [];
    Stdlib__Set_Ext.Value.Tuple2.FloatFloat.forEach(stff, v => {
      values.push(v);
    });
    return Jest.Expect.toEqual(Jest.Expect.expect(values), [
      [
        1.1,
        2.2
      ],
      [
        3.3,
        4.4
      ]
    ]);
  });
  Jest.test("has value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.FloatFloat.has(stff, [
    1.1,
    2.2
  ])), true));
  Jest.test("delete value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.FloatFloat.$$delete(stff, [
    1.1,
    2.2
  ])), true));
  Jest.test("fromArray", () => {
    let arr = [
      [
        1.1,
        2.2
      ],
      [
        3.3,
        4.4
      ]
    ];
    let stff = Stdlib__Set_Ext.Value.Tuple2.FloatFloat.fromArray(arr);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.FloatFloat.size(stff)), 2);
  });
  Jest.test("fromIterator", () => {
    let iter = Stdlib__Array_Ext.valuesIter([
      [
        1.1,
        2.2
      ],
      [
        3.3,
        4.4
      ]
    ]);
    let stff = Stdlib__Set_Ext.Value.Tuple2.FloatFloat.fromIterator(iter);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.FloatFloat.size(stff)), 2);
  });
  Jest.test("values", () => {
    let values = Stdlib__Set_Ext.Value.Tuple2.FloatFloat.values(stff).toArray();
    return Jest.Expect.toEqual(Jest.Expect.expect(values), [
      [
        1.1,
        2.2
      ],
      [
        3.3,
        4.4
      ]
    ]);
  });
  Jest.test("difference", () => {
    let stff2 = Stdlib__Set_Ext.Value.Tuple2.FloatFloat.make();
    Stdlib__Set_Ext.Value.Tuple2.FloatFloat.add(stff2, [
      3.3,
      4.4
    ]);
    let diff = Stdlib__Set_Ext.Value.Tuple2.FloatFloat.difference(stff, stff2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.FloatFloat.values(diff).toArray()), [[
        1.1,
        2.2
      ]]);
  });
  Jest.test("intersection", () => {
    let stff2 = Stdlib__Set_Ext.Value.Tuple2.FloatFloat.make();
    Stdlib__Set_Ext.Value.Tuple2.FloatFloat.add(stff2, [
      3.3,
      4.4
    ]);
    let inter = Stdlib__Set_Ext.Value.Tuple2.FloatFloat.intersection(stff, stff2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.FloatFloat.values(inter).toArray()), [[
        3.3,
        4.4
      ]]);
  });
  Jest.test("union", () => {
    let stff2 = Stdlib__Set_Ext.Value.Tuple2.FloatFloat.make();
    Stdlib__Set_Ext.Value.Tuple2.FloatFloat.add(stff2, [
      5.5,
      6.6
    ]);
    let union = Stdlib__Set_Ext.Value.Tuple2.FloatFloat.union(stff, stff2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.FloatFloat.values(union).toArray()), [
      [
        1.1,
        2.2
      ],
      [
        3.3,
        4.4
      ],
      [
        5.5,
        6.6
      ]
    ]);
  });
  Jest.test("symmetricDifference", () => {
    let stff2 = Stdlib__Set_Ext.Value.Tuple2.FloatFloat.make();
    Stdlib__Set_Ext.Value.Tuple2.FloatFloat.add(stff2, [
      3.3,
      4.4
    ]);
    Stdlib__Set_Ext.Value.Tuple2.FloatFloat.add(stff2, [
      5.5,
      6.6
    ]);
    let symDiff = Stdlib__Set_Ext.Value.Tuple2.FloatFloat.symmetricDifference(stff, stff2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.FloatFloat.values(symDiff).toArray()), [
      [
        1.1,
        2.2
      ],
      [
        5.5,
        6.6
      ]
    ]);
  });
  Jest.test("isSubsetOf", () => {
    let stff2 = Stdlib__Set_Ext.Value.Tuple2.FloatFloat.make();
    Stdlib__Set_Ext.Value.Tuple2.FloatFloat.add(stff2, [
      1.1,
      2.2
    ]);
    Stdlib__Set_Ext.Value.Tuple2.FloatFloat.add(stff2, [
      3.3,
      4.4
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.FloatFloat.isSubsetOf(stff, stff2)), true);
  });
  Jest.test("isSupersetOf", () => {
    let stff2 = Stdlib__Set_Ext.Value.Tuple2.FloatFloat.make();
    Stdlib__Set_Ext.Value.Tuple2.FloatFloat.add(stff2, [
      1.1,
      2.2
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.FloatFloat.isSupersetOf(stff, stff2)), true);
  });
  Jest.test("isDisjointFrom", () => {
    let stff2 = Stdlib__Set_Ext.Value.Tuple2.FloatFloat.make();
    Stdlib__Set_Ext.Value.Tuple2.FloatFloat.add(stff2, [
      5.5,
      6.6
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.FloatFloat.isDisjointFrom(stff, stff2)), true);
  });
  Jest.test("isEmpty returns false for non-empty set", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.FloatFloat.isEmpty(stff)), false));
  Jest.test("isEmpty returns true for empty set", () => {
    let stff2 = Stdlib__Set_Ext.Value.Tuple2.FloatFloat.make();
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.FloatFloat.isEmpty(stff2)), true);
  });
  Jest.test("toArray converts set to array", () => {
    let arr = Stdlib__Set_Ext.Value.Tuple2.FloatFloat.toArray(stff);
    return Jest.Expect.toEqual(Jest.Expect.expect(arr), [
      [
        1.1,
        2.2
      ],
      [
        3.3,
        4.4
      ]
    ]);
  });
  Jest.test("ignore discards the set", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple2.FloatFloat.ignore(stff)), undefined));
});

Jest.describe("SetTuple3IntIntInt", () => {
  let stiii = Stdlib__Set_Ext.Value.Tuple3.IntIntInt.make();
  beforeEach(() => {
    Stdlib__Set_Ext.Value.Tuple3.IntIntInt.clear(stiii);
    Stdlib__Set_Ext.Value.Tuple3.IntIntInt.add(stiii, [
      1,
      2,
      3
    ]);
    Stdlib__Set_Ext.Value.Tuple3.IntIntInt.add(stiii, [
      4,
      5,
      6
    ]);
  });
  Jest.test("clear all values", () => {
    Stdlib__Set_Ext.Value.Tuple3.IntIntInt.clear(stiii);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple3.IntIntInt.size(stiii)), 0);
  });
  Jest.test("forEach", () => {
    let values = [];
    Stdlib__Set_Ext.Value.Tuple3.IntIntInt.forEach(stiii, v => {
      values.push(v);
    });
    return Jest.Expect.toEqual(Jest.Expect.expect(values), [
      [
        1,
        2,
        3
      ],
      [
        4,
        5,
        6
      ]
    ]);
  });
  Jest.test("has value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple3.IntIntInt.has(stiii, [
    1,
    2,
    3
  ])), true));
  Jest.test("delete value", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple3.IntIntInt.$$delete(stiii, [
    1,
    2,
    3
  ])), true));
  Jest.test("fromArray", () => {
    let arr = [
      [
        1,
        2,
        3
      ],
      [
        4,
        5,
        6
      ]
    ];
    let stiii = Stdlib__Set_Ext.Value.Tuple3.IntIntInt.fromArray(arr);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple3.IntIntInt.size(stiii)), 2);
  });
  Jest.test("fromIterator", () => {
    let iter = Stdlib__Array_Ext.valuesIter([
      [
        1,
        2,
        3
      ],
      [
        4,
        5,
        6
      ]
    ]);
    let stiii = Stdlib__Set_Ext.Value.Tuple3.IntIntInt.fromIterator(iter);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple3.IntIntInt.size(stiii)), 2);
  });
  Jest.test("values", () => {
    let values = Stdlib__Set_Ext.Value.Tuple3.IntIntInt.values(stiii).toArray();
    return Jest.Expect.toEqual(Jest.Expect.expect(values), [
      [
        1,
        2,
        3
      ],
      [
        4,
        5,
        6
      ]
    ]);
  });
  Jest.test("difference", () => {
    let stiii2 = Stdlib__Set_Ext.Value.Tuple3.IntIntInt.make();
    Stdlib__Set_Ext.Value.Tuple3.IntIntInt.add(stiii2, [
      4,
      5,
      6
    ]);
    let diff = Stdlib__Set_Ext.Value.Tuple3.IntIntInt.difference(stiii, stiii2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple3.IntIntInt.values(diff).toArray()), [[
        1,
        2,
        3
      ]]);
  });
  Jest.test("intersection", () => {
    let stiii2 = Stdlib__Set_Ext.Value.Tuple3.IntIntInt.make();
    Stdlib__Set_Ext.Value.Tuple3.IntIntInt.add(stiii2, [
      4,
      5,
      6
    ]);
    let inter = Stdlib__Set_Ext.Value.Tuple3.IntIntInt.intersection(stiii, stiii2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple3.IntIntInt.values(inter).toArray()), [[
        4,
        5,
        6
      ]]);
  });
  Jest.test("union", () => {
    let stiii2 = Stdlib__Set_Ext.Value.Tuple3.IntIntInt.make();
    Stdlib__Set_Ext.Value.Tuple3.IntIntInt.add(stiii2, [
      7,
      8,
      9
    ]);
    let union = Stdlib__Set_Ext.Value.Tuple3.IntIntInt.union(stiii, stiii2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple3.IntIntInt.values(union).toArray()), [
      [
        1,
        2,
        3
      ],
      [
        4,
        5,
        6
      ],
      [
        7,
        8,
        9
      ]
    ]);
  });
  Jest.test("symmetricDifference", () => {
    let stiii2 = Stdlib__Set_Ext.Value.Tuple3.IntIntInt.make();
    Stdlib__Set_Ext.Value.Tuple3.IntIntInt.add(stiii2, [
      4,
      5,
      6
    ]);
    Stdlib__Set_Ext.Value.Tuple3.IntIntInt.add(stiii2, [
      7,
      8,
      9
    ]);
    let symDiff = Stdlib__Set_Ext.Value.Tuple3.IntIntInt.symmetricDifference(stiii, stiii2);
    return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple3.IntIntInt.values(symDiff).toArray()), [
      [
        1,
        2,
        3
      ],
      [
        7,
        8,
        9
      ]
    ]);
  });
  Jest.test("isSubsetOf", () => {
    let stiii2 = Stdlib__Set_Ext.Value.Tuple3.IntIntInt.make();
    Stdlib__Set_Ext.Value.Tuple3.IntIntInt.add(stiii2, [
      1,
      2,
      3
    ]);
    Stdlib__Set_Ext.Value.Tuple3.IntIntInt.add(stiii2, [
      4,
      5,
      6
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple3.IntIntInt.isSubsetOf(stiii, stiii2)), true);
  });
  Jest.test("isSupersetOf", () => {
    let stiii2 = Stdlib__Set_Ext.Value.Tuple3.IntIntInt.make();
    Stdlib__Set_Ext.Value.Tuple3.IntIntInt.add(stiii2, [
      1,
      2,
      3
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple3.IntIntInt.isSupersetOf(stiii, stiii2)), true);
  });
  Jest.test("isDisjointFrom", () => {
    let stiii2 = Stdlib__Set_Ext.Value.Tuple3.IntIntInt.make();
    Stdlib__Set_Ext.Value.Tuple3.IntIntInt.add(stiii2, [
      7,
      8,
      9
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple3.IntIntInt.isDisjointFrom(stiii, stiii2)), true);
  });
  Jest.test("isEmpty returns false for non-empty set", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple3.IntIntInt.isEmpty(stiii)), false));
  Jest.test("isEmpty returns true for empty set", () => {
    let stiii2 = Stdlib__Set_Ext.Value.Tuple3.IntIntInt.make();
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple3.IntIntInt.isEmpty(stiii2)), true);
  });
  Jest.test("toArray converts set to array", () => {
    let arr = Stdlib__Set_Ext.Value.Tuple3.IntIntInt.toArray(stiii);
    return Jest.Expect.toEqual(Jest.Expect.expect(arr), [
      [
        1,
        2,
        3
      ],
      [
        4,
        5,
        6
      ]
    ]);
  });
  Jest.test("ignore discards the set", () => Jest.Expect.toBe(Jest.Expect.expect(Stdlib__Set_Ext.Value.Tuple3.IntIntInt.ignore(stiii)), undefined));
});

let PrimInt;

let PrimString;

let PrimFloat;

let PrimBigInt;

let PrimSymbol;

let ArrayInt;

let ArrayString;

let ArrayFloat;

let SetTuple2IntString;

let SetTuple2FloatFloat;

let SetTuple3IntIntInt;

export {
  PrimInt,
  PrimString,
  PrimFloat,
  PrimBigInt,
  PrimSymbol,
  ArrayInt,
  ArrayString,
  ArrayFloat,
  SetTuple2IntString,
  SetTuple2FloatFloat,
  SetTuple3IntIntInt,
}
/*  Not a pure module */
