// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/rescript-jest/src/jest.mjs";
import * as Stdlib_Float from "../src/Stdlib_Float.mjs";
import * as Stdlib_String from "../src/Stdlib_String.mjs";
import * as Stdlib_Tuple2 from "../src/Stdlib_Tuple2.mjs";

Jest.test("make", (function (param) {
        return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib_Tuple2.make(3, 4)), [
                    3,
                    4
                  ]);
      }));

Jest.test("first", (function (param) {
        return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib_Tuple2.first([
                            3,
                            4
                          ])), 3);
      }));

Jest.test("second", (function (param) {
        return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib_Tuple2.second([
                            3,
                            4
                          ])), 4);
      }));

Jest.test("mapFirst", (function (param) {
        return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib_Tuple2.mapFirst([
                            "stressed",
                            16
                          ], Stdlib_String.reverse)), [
                    "desserts",
                    16
                  ]);
      }));

Jest.test("mapSecond", (function (param) {
        return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib_Tuple2.mapSecond([
                            "stressed",
                            16
                          ], Stdlib_Float.squareRoot)), [
                    "stressed",
                    4
                  ]);
      }));

Jest.test("mapEach", (function (param) {
        return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib_Tuple2.mapEach([
                            "stressed",
                            16
                          ], Stdlib_String.reverse, Stdlib_Float.squareRoot)), [
                    "desserts",
                    4
                  ]);
      }));

Jest.test("mapAll", (function (param) {
        return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib_Tuple2.mapAll([
                            "was",
                            "stressed"
                          ], Stdlib_String.reverse)), [
                    "saw",
                    "desserts"
                  ]);
      }));

Jest.test("swap", (function (param) {
        return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib_Tuple2.swap([
                            3,
                            4
                          ])), [
                    4,
                    3
                  ]);
      }));

Jest.test("toArray", (function (param) {
        return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib_Tuple2.toArray([
                            3,
                            4
                          ])), [
                    3,
                    4
                  ]);
      }));

Jest.test("toList", (function (param) {
        return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib_Tuple2.toList([
                            3,
                            4
                          ])), {
                    hd: 3,
                    tl: {
                      hd: 4,
                      tl: /* [] */0
                    }
                  });
      }));

export {
  
}
/*  Not a pure module */
