// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/rescript-jest/src/jest.mjs";
import * as Stdlib_Float from "../src/Stdlib_Float.mjs";
import * as Stdlib_String from "../src/Stdlib_String.mjs";
import * as Stdlib_Tuple4 from "../src/Stdlib_Tuple4.mjs";

Jest.test("make", (function (param) {
        return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib_Tuple4.make(3, 4, 5, 6)), [
                    3,
                    4,
                    5,
                    6
                  ]);
      }));

Jest.test("first", (function (param) {
        return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib_Tuple4.first([
                            3,
                            4,
                            5,
                            6
                          ])), 3);
      }));

Jest.test("second", (function (param) {
        return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib_Tuple4.second([
                            3,
                            4,
                            5,
                            6
                          ])), 4);
      }));

Jest.test("third", (function (param) {
        return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib_Tuple4.third([
                            3,
                            4,
                            5,
                            6
                          ])), 5);
      }));

Jest.test("forth", (function (param) {
        return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib_Tuple4.forth([
                            3,
                            4,
                            5,
                            6
                          ])), 6);
      }));

Jest.test("initial", (function (param) {
        return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib_Tuple4.initial([
                            3,
                            4,
                            5,
                            6
                          ])), [
                    3,
                    4
                  ]);
      }));

Jest.test("tail", (function (param) {
        return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib_Tuple4.tail([
                            3,
                            4,
                            5,
                            6
                          ])), [
                    5,
                    6
                  ]);
      }));

Jest.test("mapFirst", (function (param) {
        return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib_Tuple4.mapFirst([
                            "stressed",
                            16,
                            false,
                            64
                          ], Stdlib_String.reverse)), [
                    "desserts",
                    16,
                    false,
                    64
                  ]);
      }));

Jest.test("mapSecond", (function (param) {
        return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib_Tuple4.mapSecond([
                            "stressed",
                            16,
                            false,
                            64
                          ], Stdlib_Float.squareRoot)), [
                    "stressed",
                    4,
                    false,
                    64
                  ]);
      }));

Jest.test("mapThird", (function (param) {
        return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib_Tuple4.mapThird([
                            "stressed",
                            16,
                            false,
                            64
                          ], (function (prim) {
                              return !prim;
                            }))), [
                    "stressed",
                    16,
                    true,
                    64
                  ]);
      }));

Jest.test("mapEach", (function (param) {
        return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib_Tuple4.mapEach([
                            "stressed",
                            16,
                            false,
                            64
                          ], Stdlib_String.reverse, Stdlib_Float.squareRoot, (function (prim) {
                              return !prim;
                            }), Stdlib_Float.squareRoot)), [
                    "desserts",
                    4,
                    true,
                    8
                  ]);
      }));

Jest.test("mapAll", (function (param) {
        return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib_Tuple4.mapAll([
                            "was",
                            "stressed",
                            "now",
                            "but"
                          ], Stdlib_String.reverse)), [
                    "saw",
                    "desserts",
                    "won",
                    "tub"
                  ]);
      }));

Jest.test("rotateLeft", (function (param) {
        return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib_Tuple4.rotateLeft([
                            3,
                            4,
                            5,
                            6
                          ])), [
                    4,
                    5,
                    6,
                    3
                  ]);
      }));

Jest.test("rotateRight", (function (param) {
        return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib_Tuple4.rotateRight([
                            3,
                            4,
                            5,
                            6
                          ])), [
                    6,
                    3,
                    4,
                    5
                  ]);
      }));

Jest.test("toArray", (function (param) {
        return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib_Tuple4.toArray([
                            3,
                            4,
                            5,
                            6
                          ])), [
                    3,
                    4,
                    5,
                    6
                  ]);
      }));

Jest.test("toList", (function (param) {
        return Jest.Expect.toEqual(Jest.Expect.expect(Stdlib_Tuple4.toList([
                            3,
                            4,
                            5,
                            6
                          ])), {
                    hd: 3,
                    tl: {
                      hd: 4,
                      tl: {
                        hd: 5,
                        tl: {
                          hd: 6,
                          tl: /* [] */0
                        }
                      }
                    }
                  });
      }));

export {
  
}
/*  Not a pure module */
